<?xml version="1.0" encoding="utf-8"?>
<bundle name="Captions" type="Caption" culture="en">
  <data id="01">&lt;s:data id="_0" f:Labels="{Collection {Text 'Bold'}}" /&gt;</data>
  <data id="08">&lt;s:data id="_0" f:Labels="{Collection {Text 'Default font'}}" /&gt;</data>
  <data id="04">&lt;objects xmlns:s="*1" xmlns:f="*1"&gt;&lt;s:storage s:root="_1" s:n_ext="0" s:n_typ="2" s:n_obj="2"&gt;&lt;s:type id="_1" s:name="*C" /&gt;&lt;s:type id="_2" s:name="Epsitec.Common.Widgets.Shortcut" /&gt;&lt;s:object id="_1" s:type="_1" /&gt;&lt;s:object id="_2" s:type="_2" /&gt;&lt;s:data id="_1" f:_2.Shortcuts="{Collection {ObjRef _2}}" f:Labels="{Collection {Text 'Italic'}}" /&gt;&lt;s:data id="_2" f:KeyCode="AlphaI, ModifierControl" /&gt;&lt;/s:storage&gt;&lt;/objects&gt;</data>
  <data id="07">&lt;s:type id="_1" s:name="Epsitec.Common.Widgets.Command" /&gt;&lt;s:data id="_0" f:_1.Statefull="False" f:_1.DefaultParameter="{Null}" f:Labels="{Collection {Text 'Larger font'}}" /&gt;</data>
  <data id="06">&lt;s:type id="_1" s:name="Epsitec.Common.Widgets.Command" /&gt;&lt;s:data id="_0" f:_1.Statefull="False" f:_1.DefaultParameter="{Null}" f:Labels="{Collection {Text 'Smaller font'}}" /&gt;</data>
  <data id="05">&lt;s:data id="_0" f:Labels="{Collection {Text 'Underline'}}" /&gt;</data>
</bundle>