<?xml version="1.0" encoding="utf-8"?>
<bundle name="Strings" type="String" culture="fr">
  <data name="Directory.OriginalSamples" id="01A01" mod="1" about="NE PAS MODIFIER (nom de dossier)">Exemples originaux</data>
  <data name="Directory.MySamples" id="02A01" mod="2" about="NE PAS MODIFIER (nom de dossier)">Exemples modifiés</data>
  <data name="Directory.MyDocumentsRoot" id="0FA01" about="NE PAS MODIFIER (nom de dossier)">Crésus Documents</data>
  <data name="Dialog.Title" id="0">Crésus</data>
  <data name="Dialog.Button.Browse" id="01">Parcourir...</data>
  <data name="Dialog.Button.Properties" id="02">Attributs...</data>
  <data name="Dialog.Button.More" id="03">Etend ou réduit le panneau</data>
  <data name="Dialog.Point.Link" id="04">Liés</data>
  <data name="Dialog.Settings.SizeDoc" id="05">Dimensions d&amp;apos;une page</data>
  <data name="Dialog.Settings.SizePic" id="06">Dimensions d&amp;apos;un pictogramme</data>
  <data name="Dialog.Settings.Grid" id="07">Grille magnétique</data>
  <data name="Dialog.Settings.TextGrid" id="08">Lignes magnétiques pour le texte</data>
  <data name="Dialog.Settings.Magnet" id="09">Repères magnétiques</data>
  <data name="Dialog.Settings.DuplicateMove" id="0A">Déplacement lorsqu&amp;apos;un objet est dupliqué</data>
  <data name="Dialog.Settings.ArrowMove" id="0B">Déplacement avec les touches flèches</data>
  <data name="Dialog.Settings.Dimension" id="0C">Valeurs des cotes</data>
  <data name="Dialog.Settings.ToLinePrecision" id="0D">Convertir en droites et opérations booléennes</data>
  <data name="Dialog.Settings.Constrain" id="09C01">Déplacement avec les contraintes</data>
  <data name="Dialog.Settings.FirstAction.Nothing" id="0E">Rien</data>
  <data name="Dialog.Settings.FirstAction.OpenNewDocument" id="0F">Ouvrir un document vide</data>
  <data name="Dialog.Settings.FirstAction.OpenLastModel" id="0T901" mod="1">Ouvrir le dernier modèle</data>
  <data name="Dialog.Settings.FirstAction.OpenLastModels" id="0U901" mod="1">Ouvrir les derniers modèles</data>
  <data name="Dialog.Settings.FirstAction.OpenLastFile" id="0G">Ouvrir le dernier document</data>
  <data name="Dialog.Settings.FirstAction.OpenLastFiles" id="0H">Ouvrir les derniers documents</data>
  <data name="Dialog.Settings.MouseWheelAction.Zoom" id="0I">Loupe</data>
  <data name="Dialog.Settings.MouseWheelAction.VScroll" id="0J">Défilement vertical</data>
  <data name="Dialog.Settings.Fonts.Title" id="0K">Polices fréquemment utilisées, en tête de liste</data>
  <data name="Dialog.Settings.Fonts.Default" id="0L">Polices les plus courantes</data>
  <data name="Dialog.Settings.Fonts.Clear" id="0M">Aucune police fréquement utilisée</data>
  <data name="Dialog.Print.Printer" id="0N">Choix de l&amp;apos;imprimante</data>
  <data name="Dialog.Print.Properties" id="0O">Propriétés</data>
  <data name="Dialog.Print.Area" id="0P">Etendue</data>
  <data name="Dialog.Print.Copies" id="0Q">Tirage</data>
  <data name="Dialog.Print.Param" id="0R">Paramètres pour l&amp;apos;impression</data>
  <data name="Dialog.Print.File" id="0S">Fichier</data>
  <data name="Dialog.Print.Image" id="0CA01" mod="1">Images bitmap</data>
  <data name="Dialog.Print.Publisher" id="0T">Réglages pré-presse</data>
  <data name="Dialog.Print.ToFile.Title" id="0U">Impression dans un fichier</data>
  <data name="Dialog.Print.ToFile.Type" id="0V">Fichier d&amp;apos;impression</data>
  <data name="Dialog.Print.Paper.Direction" id="001">Orientation</data>
  <data name="Dialog.Print.Paper.Portrait" id="011">Portrait</data>
  <data name="Dialog.Print.Paper.Landscape" id="021">Paysage</data>
  <data name="Dialog.Print.Paper.PaperList" id="031">Papier</data>
  <data name="Dialog.Print.Range.All" id="041">Toutes les pages</data>
  <data name="Dialog.Print.Range.From" id="051">Pages de</data>
  <data name="Dialog.Print.Range.To" id="061">à</data>
  <data name="Dialog.Print.Range.Current" id="071">Page courante</data>
  <data name="Dialog.Print.Format.User" id="081">Personnalisé</data>
  <data name="Dialog.Export.Generic" id="091">Géométrie de l&amp;apos;image exportée</data>
  <data name="Dialog.Export.Format" id="0SB01">Format de l&amp;apos;image exportée</data>
  <data name="Dialog.Export.Filter" id="0TB01">Filtrage des images contenues</data>
  <data name="Dialog.ExportPDF.Param" id="0A1">Paramètres pour le document à exporter en PDF</data>
  <data name="Dialog.ExportICO.Param" id="0LA01">Choix pour l&amp;apos;exportation de l&amp;apos;icône</data>
  <data name="Dialog.ExportPDF.Publisher" id="0B1">Réglages pré-presse</data>
  <data name="Dialog.ExportPDF.BleedEven" id="0KB01">Débords additionnels (page paire)</data>
  <data name="Dialog.ExportPDF.BleedOdd" id="0LB01">Débords additionnels (page impaire)</data>
  <data name="Dialog.Bool.GridActive" id="0C1">Grille active</data>
  <data name="Dialog.Bool.ImageOnlySelected" id="0PB01">Exporter seulement les objets sélectionnés</data>
  <data name="Dialog.Bool.GridShow" id="0D1">Grille visible</data>
  <data name="Dialog.Bool.TextGridShow" id="0E1">Lignes visibles</data>
  <data name="Dialog.Bool.TextShowControlCharacters" id="0F1">Afficher les caractères spéciaux</data>
  <data name="Dialog.Bool.TextFontFilter" id="0G1">Seulement les caractères fréquement utilisés</data>
  <data name="Dialog.Bool.TextFontSampleAbc" id="0H1">Afficher &amp;apos;Abc&amp;apos; au lieu de &amp;apos;AaBbYyZz&amp;apos;</data>
  <data name="Dialog.Bool.GuidesActive" id="0I1">Repères actifs</data>
  <data name="Dialog.Bool.GuidesShow" id="0J1">Repères visibles</data>
  <data name="Dialog.Bool.GuidesMouse" id="0K1">Déplacements avec la souris</data>
  <data name="Dialog.Bool.PreviewActive" id="0L1">Comme imprimé</data>
  <data name="Dialog.Bool.RulersShow" id="0M1">Règles visibles</data>
  <data name="Dialog.Bool.LabelsShow" id="0N1">Affiche le nom des objets</data>
  <data name="Dialog.Bool.MagnetActive" id="0O1">Objets magnétiques</data>
  <data name="Dialog.Bool.PrintCollate" id="0P1">Copies assemblées (1,2,3 - 1,2,3)</data>
  <data name="Dialog.Bool.PrintReverse" id="0Q1">Ordre inversé</data>
  <data name="Dialog.Bool.PrintToFile" id="0R1">Imprimer dans un fichier</data>
  <data name="Dialog.Bool.PrintDraft" id="0S1">Brouillon (pas de dégradé ni de transparence)</data>
  <data name="Dialog.Bool.PrintAutoLandscape" id="0T1">Portrait/paysage automatique</data>
  <data name="Dialog.Bool.PrintAutoZoom" id="0U1">Adapter l&amp;apos;impression à la taille de la page</data>
  <data name="Dialog.Bool.PrintAA" id="0V1">Anti-crénelage (pour imprimante couleur)</data>
  <data name="Dialog.Bool.PrintPerfectJoin" id="002">Jointures parfaites (entre les zones d&amp;apos;une page)</data>
  <data name="Dialog.Bool.PrintTarget" id="012">Traits de coupe (hors de la page)</data>
  <data name="Dialog.Bool.PrintDebugArea" id="022">Imprime les zones détectées (debug)</data>
  <data name="Dialog.Bool.ExportPDFTarget" id="032">Traits de coupe (hors de la page)</data>
  <data name="Export.PDF.Progress.Init" id="00B01">Initialisation</data>
  <data name="Export.PDF.Progress.Ressource" id="01B01">Génération des ressource {0}</data>
  <data name="Export.PDF.Progress.Content" id="02B01">Génération du contenu {0}</data>
  <data name="Export.PDF.Progress.Cancelled" id="05B01">Exportation annulée.</data>
  <data name="Export.PDF.Progress.Image" id="03B01">Génération des images {0}</data>
  <data name="Export.PDF.Progress.Surface" id="04B01">Génération des surfaces {0}.{1}</data>
  <data name="Dialog.Bool.ExportPDFTextCurve" id="042">Textes en courbes</data>
  <data name="Dialog.Bool.RepeatDuplicateMove" id="052">Duplique avec répétition du dernier déplacement</data>
  <data name="Dialog.Double.OutsideArea" id="062">Zone hors page</data>
  <data name="Dialog.Double.PrintCopies" id="072">Nombre de copies</data>
  <data name="Dialog.Double.PrintDpi" id="082">Résolution (dpi)</data>
  <data name="Dialog.Double.PrintMargins" id="092">Marges de centrage</data>
  <data name="Dialog.Double.PrintDebord" id="0A2">Débord</data>
  <data name="Dialog.Double.ExportPDFBleed" id="0B2">Débord</data>
  <data name="Dialog.Double.ExportPDFBleedEvenTop" id="0CB01">Haut</data>
  <data name="Dialog.Double.ExportPDFBleedOddTop" id="0JB01">Haut</data>
  <data name="Dialog.Double.ExportPDFBleedEvenBottom" id="0DB01">Bas</data>
  <data name="Dialog.Double.ExportPDFBleedOddBottom" id="0GB01">Bas</data>
  <data name="Dialog.Double.ExportPDFBleedEvenLeft" id="0EB01">Gauche</data>
  <data name="Dialog.Double.ExportPDFBleedOddLeft" id="0HB01">Gauche</data>
  <data name="Dialog.Double.ExportPDFBleedEvenRight" id="0FB01">Droite</data>
  <data name="Dialog.Double.ExportPDFBleedOddRight" id="0IB01">Droite</data>
  <data name="Dialog.Double.ExportPDFJpegQuality" id="0C2">Qualité des images</data>
  <data name="Dialog.Double.ExportPDFImageMinDpi" id="0D2">Résolution min. (dpi)</data>
  <data name="Dialog.Double.ExportPDFImageMaxDpi" id="0E2">Résolution max. (dpi)</data>
  <data name="Dialog.Double.ImageDpi" id="0F2">Résolution (dpi)</data>
  <data name="Dialog.Double.ImageDpiWidth" id="01C01">Largeur en pixels</data>
  <data name="Dialog.Double.ImageDpiHeight" id="02C01">Hauteur en pixels</data>
  <data name="Dialog.Double.ImageQuality" id="0G2">Qualité de l&amp;apos;image</data>
  <data name="Dialog.Double.ImageQuality1" id="0H2">Qualité minimale, taille faible</data>
  <data name="Dialog.Double.ImageQuality2" id="0I2">Basse qualité, taille faible</data>
  <data name="Dialog.Double.ImageQuality3" id="0J2">Qualité moyenne, taille standard</data>
  <data name="Dialog.Double.ImageQuality4" id="0K2">Bonne qualité, taille importante</data>
  <data name="Dialog.Double.ImageQuality5" id="0L2">Qualité maximale, taille importante</data>
  <data name="Dialog.Double.ImageAA" id="0M2">Anti-crénelage</data>
  <data name="Dialog.Double.ImageAA1" id="0N2">Escaliers importants (tout ou rien)</data>
  <data name="Dialog.Double.ImageAA2" id="0O2">Escaliers prononcés</data>
  <data name="Dialog.Double.ImageAA3" id="0P2">Adoucissement moyen</data>
  <data name="Dialog.Double.ImageAA4" id="0Q2">Adoucissement important</data>
  <data name="Dialog.Double.ImageAA5" id="0R2">Adoucissement maximal (standard)</data>
  <data name="Dialog.Double.ArrowMoveMul" id="0S2">Multiplicateur si Shift</data>
  <data name="Dialog.Double.ArrowMoveDiv" id="0T2">Diviseur si Ctrl</data>
  <data name="Dialog.Double.ToLinePrecision" id="0U2">Précision</data>
  <data name="Dialog.Double.DimensionScale" id="0V2">Echelle</data>
  <data name="Dialog.Double.DimensionDecimal" id="003">Nombre de décimales</data>
  <data name="Dialog.Double.TextFontSampleHeight" id="013">Taille des échantillons</data>
  <data name="Dialog.Integer.DefaultUnit.Text" id="023">Unité de travail</data>
  <data name="Dialog.Integer.DefaultUnit.Millimeter" id="033">Millimètres</data>
  <data name="Dialog.Integer.DefaultUnit.Centimeter" id="043">Centimètres</data>
  <data name="Dialog.Integer.DefaultUnit.Inch" id="053">Pouces</data>
  <data name="Dialog.Integer.PrintArea.Text" id="063">Imprimer</data>
  <data name="Dialog.Integer.ImageCrop.Page" id="0UB01">Sur la page</data>
  <data name="Dialog.Integer.ImageCrop.Objects" id="0VB01">Sur les objets</data>
  <data name="Dialog.Integer.ImageCrop.Selection" id="00C01">Sur la sélection</data>
  <data name="Dialog.Integer.PrintArea.All" id="073">Toutes les pages</data>
  <data name="Dialog.Integer.PrintArea.Even" id="083">Les pages paires</data>
  <data name="Dialog.Integer.PrintArea.Odd" id="093">Les pages impaires</data>
  <data name="Dialog.Integer.PrintCentring.Text" id="0A3">Position dans la page</data>
  <data name="Dialog.Integer.PrintCentring.BottomLeft" id="0B3">Calé en bas à gauche</data>
  <data name="Dialog.Integer.PrintCentring.BottomCenter" id="0C3">Centré en bas</data>
  <data name="Dialog.Integer.PrintCentring.BottomRight" id="0D3">Calé en bas à droite</data>
  <data name="Dialog.Integer.PrintCentring.MiddleLeft" id="0E3">Centré à gauche</data>
  <data name="Dialog.Integer.PrintCentring.MiddleCenter" id="0F3">Centré</data>
  <data name="Dialog.Integer.PrintCentring.MiddleRight" id="0G3">Centré à droite</data>
  <data name="Dialog.Integer.PrintCentring.TopLeft" id="0H3">Calé en haut à gauche</data>
  <data name="Dialog.Integer.PrintCentring.TopCenter" id="0I3">Centré en haut</data>
  <data name="Dialog.Integer.PrintCentring.TopRight" id="0J3">Calé en haut à droite</data>
  <data name="Dialog.Integer.ImageDepth.Text" id="0K3">Nombre de couleurs</data>
  <data name="Dialog.Integer.ImageDepth.Bit2" id="0L3">Noir et blanc (1 bit)</data>
  <data name="Dialog.Integer.ImageDepth.Bit8" id="0M3">256 (8 bits)</data>
  <data name="Dialog.Integer.ImageDepth.Bit16" id="0N3">65&amp;apos;000 (16 bits)</data>
  <data name="Dialog.Integer.ImageDepth.Bit24" id="0O3">16 millions (24 bits)</data>
  <data name="Dialog.Integer.ImageDepth.Bit32" id="0P3">Avec transparence (32 bits)</data>
  <data name="Dialog.Integer.ImageCompression.Text" id="0Q3">Type de compression</data>
  <data name="Dialog.Integer.ImageCrop.Text" id="03C01">Cadrage de l&amp;apos;image</data>
  <data name="Dialog.Integer.ConstrainAngle.Text" id="04C01">Angles supplémentaires</data>
  <data name="Dialog.Integer.ConstrainAngle.None" id="05C01">Aucun</data>
  <data name="Dialog.Integer.ConstrainAngle.Quarter" id="06C01">45°</data>
  <data name="Dialog.Integer.ConstrainAngle.Sixth" id="07C01">30° et 60°</data>
  <data name="Dialog.Integer.ConstrainAngle.Eight" id="08C01">22.5°, 45° et 67.5°</data>
  <data name="Dialog.Integer.ImageCompression.None" id="0R3">Aucune</data>
  <data name="Dialog.Integer.ImageCompression.Lzw" id="0S3">LZW</data>
  <data name="Dialog.Integer.ImageCompression.Rle" id="0T3">RLE</data>
  <data name="Dialog.Integer.ImageCompression.FaxGroup3" id="0U3">Fax Group 3</data>
  <data name="Dialog.Integer.ImageCompression.FaxGroup4" id="0V3">Fax Group 4</data>
  <data name="Dialog.Integer.ImageFilterA.Text" id="07A01" mod="1">Filtrage du groupe A</data>
  <data name="Dialog.Integer.ImageFilterB.Text" id="08A01" mod="1">Filtrage du groupe B</data>
  <data name="Dialog.Integer.ExportPDFColorConversion.Text" id="004">Conversion</data>
  <data name="Dialog.Integer.ExportPDFColorConversion.None" id="014">Aucune</data>
  <data name="Dialog.Integer.ExportICOFormat.Text" id="0MA01">Format</data>
  <data name="Dialog.Integer.ExportICOFormat.XP" id="0NA01">Windows XP</data>
  <data name="Dialog.Integer.ExportICOFormat.Vista" id="0OA01">Windows Vista</data>
  <data name="Dialog.Integer.ExportPDFColorConversion.ToRgb" id="024">Couleurs en RVB</data>
  <data name="Dialog.Integer.ExportPDFColorConversion.ToCmyk" id="034">Couleurs en CMJN</data>
  <data name="Dialog.Integer.ExportPDFColorConversion.ToGray" id="044">Couleurs en niveaux de gris</data>
  <data name="Dialog.Integer.ExportPDFImageCompression.Text" id="054">Compression</data>
  <data name="Dialog.Integer.ExportPDFImageCompression.None" id="064">Aucune</data>
  <data name="Dialog.Integer.ExportPDFImageCompression.ZIP" id="074">Sans pertes (zip)</data>
  <data name="Dialog.Integer.ExportPDFImageCompression.JPEG" id="084">Avec pertes (jpeg)</data>
  <data name="Dialog.Point.PageSizeX" id="094">Largeur</data>
  <data name="Dialog.Point.PageSizeY" id="0A4">Hauteur</data>
  <data name="Dialog.Point.GridStepX" id="0B4">Pas horizontal</data>
  <data name="Dialog.Point.GridStepY" id="0C4">Pas vertical</data>
  <data name="Dialog.Point.GridSubdivX" id="0D4">Subdivisions horizontales</data>
  <data name="Dialog.Point.GridSubdivY" id="0E4">Subdivisions vertitales</data>
  <data name="Dialog.Point.GridOffsetX" id="0F4">Décalage horizontal</data>
  <data name="Dialog.Point.GridOffsetY" id="0G4">Décalage vertical</data>
  <data name="Dialog.Point.DuplicateMoveX" id="0H4">Déplacement à droite</data>
  <data name="Dialog.Point.DuplicateMoveY" id="0I4">Déplacement en haut</data>
  <data name="Dialog.Point.ArrowMoveX" id="0J4">Déplacement horizontal</data>
  <data name="Dialog.Point.ArrowMoveY" id="0K4">Déplacement vertical</data>
  <data name="Units.Short.Millimeter" id="0L4">mm</data>
  <data name="Units.Short.Centimeter" id="0M4">cm</data>
  <data name="Units.Short.Inch" id="0N4">in</data>
  <data name="Units.Long.Millimeter" id="0O4">millimètres</data>
  <data name="Units.Long.Centimeter" id="0P4">centimètres</data>
  <data name="Units.Long.Inch" id="0Q4">pouces</data>
  <data name="Container.Help.Principal" id="0R4">● Attributs des objets créés ou sélectionnés :</data>
  <data name="Container.Help.Styles" id="0S4">● Réglages des styles du document :</data>
  <data name="Container.Help.Pages" id="0T4">● Réglages des pages du document :</data>
  <data name="Container.Help.Layers" id="0U4">● Réglages des calques de la page courante :</data>
  <data name="Container.Guides.RadioGlobal" id="0V4">Document</data>
  <data name="Container.Guides.RadioPage" id="005">Page courante</data>
  <data name="Container.Guides.Header.Type" id="015">Type</data>
  <data name="Container.Guides.Header.Position" id="025">Position</data>
  <data name="Container.Guides.Undefined" id="035">&lt;i&gt;indéfini &lt;/i&gt;</data>
  <data name="Container.Guides.HorizontalBottom" id="045">Horizontal, depuis le bas</data>
  <data name="Container.Guides.HorizontalCenter" id="055">Horizontal, centré</data>
  <data name="Container.Guides.HorizontalTop" id="065">Horizontal, depuis le haut</data>
  <data name="Container.Guides.VerticalLeft" id="075">Vertical, depuis la gauche</data>
  <data name="Container.Guides.VerticalCenter" id="085">Vertical, centré</data>
  <data name="Container.Guides.VerticalRight" id="095">Vertical, depuis la droite</data>
  <data name="Container.Layers.Button.Show" id="0A5">Afficher tous</data>
  <data name="Container.Layers.Button.Dimmed" id="0B5">Estomper les autres</data>
  <data name="Container.Layers.Button.Hide" id="0C5">Cacher les autres</data>
  <data name="Container.Layers.Button.HelpShow" id="0D5">Afficher normalement tous les calques</data>
  <data name="Container.Layers.Button.HelpDimmed" id="0E5">Afficher estompé les autres calques</data>
  <data name="Container.Layers.Button.HelpHide" id="0F5">Cacher les autres calques</data>
  <data name="Container.Layers.Button.PrintGroup" id="0G5">Si impression :</data>
  <data name="Container.Layers.Button.PrintShow" id="0H5">Imprimer</data>
  <data name="Container.Layers.Button.PrintDimmed" id="0I5">Estomper</data>
  <data name="Container.Layers.Button.PrintHide" id="0J5">Cacher</data>
  <data name="Container.Layers.Header.Position" id="0K5">Position</data>
  <data name="Container.Layers.Header.Name" id="0L5">Nom</data>
  <data name="Container.Layers.Header.Magnet" id="0M5">M</data>
  <data name="Container.Layers.Header.Show" id="0N5">V</data>
  <data name="Container.Layers.Tooltip.Show" id="0O5">Visibilité du calque</data>
  <data name="Container.Pages.Button.Slave" id="0P5">Page normale</data>
  <data name="Container.Pages.Button.Master" id="0Q5">Page modèle</data>
  <data name="Container.Pages.Button.PageStack" id="0R5">Structure de la page...</data>
  <data name="Container.Pages.Button.SlaveGroup" id="0S5">Inclure les pages modèles ?</data>
  <data name="Container.Pages.Button.SlaveNever" id="0T5">Non</data>
  <data name="Container.Pages.Button.SlaveDefault" id="0U5">Oui</data>
  <data name="Container.Pages.Button.SlaveSpecific" id="0V5">Inclure cette page modèle</data>
  <data name="Container.Pages.Button.SlaveGuides" id="006">Inclure les repères</data>
  <data name="Container.Pages.Button.MasterGroup" id="016">Destination :</data>
  <data name="Container.Pages.Button.MasterAll" id="026">Appliquer à toutes les pages</data>
  <data name="Container.Pages.Button.MasterOdd" id="036">Appliquer aux pages impaires</data>
  <data name="Container.Pages.Button.MasterEven" id="046">Appliquer aux pages paires</data>
  <data name="Container.Pages.Button.MasterNone" id="056">Appliquer à la demande</data>
  <data name="Container.Pages.Button.MasterStop" id="066">Stopper à la prochaine page modèle</data>
  <data name="Container.Pages.Button.MasterSpecific" id="076">Inclure cette page modèle</data>
  <data name="Container.Pages.Header.Number" id="086">N°</data>
  <data name="Container.Pages.Header.Name" id="096">Nom</data>
  <data name="Container.Pages.Size.Label" id="0A6">Dimensions page</data>
  <data name="Container.Pages.Size.Width" id="0B6">Largeur de cette page</data>
  <data name="Container.Pages.Size.Height" id="0C6">Hauteur de cette page</data>
  <data name="Container.Pages.Size.Swap" id="0D6">Portrait - paysage</data>
  <data name="Container.Pages.Size.Clear" id="0E6">Dimensions standards</data>
  <data name="Container.Pages.Language.Label" id="0F6">Langue page</data>
  <data name="Container.Pages.Style.Label" id="0G6">Style page</data>
  <data name="Container.Principal.Button.Detail" id="0H6">Détails</data>
  <data name="Container.Principal.Button.Auto" id="0I6">Sélection automatique</data>
  <data name="Container.Principal.Button.Individual" id="0J6">Sélectionne les objets individuellement</data>
  <data name="Container.Principal.Button.Scaler" id="0K6">Déplacement, agrandissement et rotation</data>
  <data name="Container.Principal.Button.Stretch" id="0L6">Déformation</data>
  <data name="Container.Principal.Button.StretchType" id="0M6">Type de déformation</data>
  <data name="Container.Principal.Button.Total" id="0N6">Sélection totale requise</data>
  <data name="Container.Principal.Button.Partial" id="0O6">Sélection partielle autorisée</data>
  <data name="Container.Principal.Button.AdaptLine" id="0P6">Adapte les traits</data>
  <data name="Container.Principal.Button.AdaptText" id="0Q6">Adapte les textes</data>
  <data name="Container.Principal.Button.SelName" id="0R6">Nom de l&amp;apos;objet à sélectionner</data>
  <data name="Container.Principal.Button.SelGo" id="0S6">Sélectionner</data>
  <data name="Container.Principal.Button.SelGoHelp" id="0T6">Sélectionne l&amp;apos;objet selon le nom</data>
  <data name="Container.Principal.Menu.Stretch.Free" id="0U6">Déformation libre</data>
  <data name="Container.Principal.Menu.Stretch.TrapezeH" id="0V6">Déformation en trapèze horizontal</data>
  <data name="Container.Principal.Menu.Stretch.TrapezeV" id="007">Déformation en trapèze vertical</data>
  <data name="Container.Principal.Menu.Stretch.ParallelH" id="017">Déformation en parallélogramme horizontal</data>
  <data name="Container.Principal.Menu.Stretch.ParallelV" id="027">Déformation en parallélogramme vertical</data>
  <data name="Container.Principal.Button.AggregateLabel" id="037">Style</data>
  <data name="Container.Principal.Button.AggregateCombo" id="047">Nom du style</data>
  <data name="Object.Abstract.InfoLine" id="057">lg={0} α={1}</data>
  <data name="Object.Abstract.InfoRectangle" id="067">dx={0} dy={1}</data>
  <data name="Object.Abstract.InfoCircle" id="077">r={0}</data>
  <data name="Object.Bezier.Menu.ToCurve" id="087">Courbe</data>
  <data name="Object.Bezier.Menu.ToLine" id="097">Droit</data>
  <data name="Object.Bezier.Menu.HandleAdd" id="0A7">Ajouter un point</data>
  <data name="Object.Bezier.Menu.HandleSym" id="0B7">Symétrique</data>
  <data name="Object.Bezier.Menu.HandleSmooth" id="0C7">Lisse</data>
  <data name="Object.Bezier.Menu.HandleCorner" id="0D7">Anguleux</data>
  <data name="Object.Bezier.Menu.HandleLine" id="0E7">En ligne</data>
  <data name="Object.Bezier.Menu.HandleFree" id="0F7">Libre</data>
  <data name="Object.Bezier.Menu.HandleContinue" id="0G7">Prolonger le trait</data>
  <data name="Object.Bezier.Menu.HandleDelete" id="0H7">Enlever le point</data>
  <data name="Object.Bezier.Info" id="0I7">lg={0} α={1}</data>
  <data name="Object.Poly.Menu.HandleAdd" id="0J7">Ajouter un point</data>
  <data name="Object.Poly.Menu.HandleSym" id="0K7">Coin quelconque</data>
  <data name="Object.Poly.Menu.HandleSimply" id="0L7">Coin toujours droit</data>
  <data name="Object.Poly.Menu.HandleContinue" id="0M7">Prolonger le trait</data>
  <data name="Object.Poly.Menu.HandleDelete" id="0N7">Enlever le point</data>
  <data name="Object.Poly.Info1" id="0O7">lg={0} α={1}</data>
  <data name="Object.Poly.Info2" id="0P7">lg={0} α={2}  |  lg={1} α={3}</data>
  <data name="Object.Button.CreateEndingOpen" id="0Q7">Terminer en l&amp;apos;état</data>
  <data name="Object.Button.CreateEndingClose" id="0GA01">Terminer et fermer</data>
  <data name="Object.Button.CreateAndSelect" id="0R7">Terminer et sélectionner</data>
  <data name="Object.Button.CreateAndShaper" id="0S7">Terminer et modeler</data>
  <data name="Object.Text.Error" id="0T7">La police &lt;b&gt;{0}&lt;/b&gt; n&amp;apos;existe pas.</data>
  <data name="Object.Image.Error" id="0U7">Le fichier &lt;b&gt;{0}&lt;/b&gt; n&amp;apos;existe pas.</data>
  <data name="Panel.Abstract.Extend" id="0V7">Etend ou réduit le panneau</data>
  <data name="Panel.Style.ParagraphDefinition" id="008">Choix des styles de paragraphe</data>
  <data name="Panel.Style.CharacterDefinition" id="018">Choix des styles de caractère</data>
  <data name="Panel.AggregateCategory.Graphic" id="028">Graphique</data>
  <data name="Panel.AggregateCategory.Paragraph" id="038">Paragraphe</data>
  <data name="Panel.AggregateCategory.Character" id="048">Caractère</data>
  <data name="Panel.AggregateName.Label.Name" id="058">Nom</data>
  <data name="Panel.AggregateName.Tooltip.Name" id="068">Nom du style</data>
  <data name="Panel.AggregateChildren.Label.Name" id="078">Basé sur</data>
  <data name="Panel.AggregateChildren.Tooltip.Name" id="088">Styles de base</data>
  <data name="Panel.AggregateChildren.Tooltip.Menu" id="098">Choix des styles de base</data>
  <data name="Panel.Arc.Short.Initial" id="0A8">α1</data>
  <data name="Panel.Arc.Short.Final" id="0B8">α2</data>
  <data name="Panel.Arc.Long.Initial" id="0C8">Angle initial</data>
  <data name="Panel.Arc.Long.Final" id="0D8">Angle final</data>
  <data name="Panel.Arc.Tooltip.Initial" id="0E8">Angle initial en degrés</data>
  <data name="Panel.Arc.Tooltip.Final" id="0F8">Angle final en degrés</data>
  <data name="Panel.Arrow.Short.Length" id="0G8">L</data>
  <data name="Panel.Arrow.Short.Effect1" id="0H8">A</data>
  <data name="Panel.Arrow.Short.Effect2" id="0I8">B</data>
  <data name="Panel.Arrow.Long.Length" id="0J8">Longueur</data>
  <data name="Panel.Arrow.Long.Effect1" id="0K8">Variante A</data>
  <data name="Panel.Arrow.Long.Effect2" id="0L8">Variante B</data>
  <data name="Panel.Arrow.Tooltip.Length" id="0M8">Longueur de l&amp;apos;extrémité</data>
  <data name="Panel.Arrow.Tooltip.Effect1" id="0N8">Variante A de l&amp;apos;extrémité</data>
  <data name="Panel.Arrow.Tooltip.Effect2" id="0O8">Variante B de l&amp;apos;extrémité</data>
  <data name="Panel.Arrow.Tooltip.Swap" id="0P8">Permute les extrémités</data>
  <data name="Panel.Color.Tooltip.Main" id="0Q8">Couleur</data>
  <data name="Panel.Corner.Short.Radius" id="0R8">R</data>
  <data name="Panel.Corner.Short.Effect1" id="0S8">A</data>
  <data name="Panel.Corner.Short.Effect2" id="0T8">B</data>
  <data name="Panel.Corner.Long.Radius" id="0U8">Rayon</data>
  <data name="Panel.Corner.Long.Effect1" id="0V8">Variante A</data>
  <data name="Panel.Corner.Long.Effect2" id="009">Variante B</data>
  <data name="Panel.Corner.Tooltip.Radius" id="019">Rayon du coin</data>
  <data name="Panel.Corner.Tooltip.Effect1" id="029">Variante A du coin</data>
  <data name="Panel.Corner.Tooltip.Effect2" id="039">Variante B du coin</data>
  <data name="Panel.Dimension.Short.AddLength" id="049">L</data>
  <data name="Panel.Dimension.Short.OutLength" id="059">E</data>
  <data name="Panel.Dimension.Short.FontOffset" id="069">V</data>
  <data name="Panel.Dimension.Short.Text" id="079">T</data>
  <data name="Panel.Dimension.Long.AddLength" id="089">Débordement des traits</data>
  <data name="Panel.Dimension.Long.OutLength" id="099">Longueur cote extérieure</data>
  <data name="Panel.Dimension.Long.FontOffset" id="0A9">Décalage vertical du texte</data>
  <data name="Panel.Dimension.Long.Text" id="0B9">Texte de la cote</data>
  <data name="Panel.Dimension.Tooltip.AddLength" id="0C9">Débordement des traits de support</data>
  <data name="Panel.Dimension.Tooltip.OutLength" id="0D9">Longueur si cote extérieure</data>
  <data name="Panel.Dimension.Tooltip.RotateText" id="0E9">Texte inversé</data>
  <data name="Panel.Dimension.Tooltip.FontOffset" id="0F9">Décalage vertical du texte</data>
  <data name="Panel.Dimension.Tooltip.Text" id="0G9">Texte de la cote (# = valeur cote)</data>
  <data name="Panel.Font.Short.Size" id="0H9">T</data>
  <data name="Panel.Font.Short.Color" id="0I9">C</data>
  <data name="Panel.Font.Long.Size" id="0J9">Taille par défaut</data>
  <data name="Panel.Font.Long.Color" id="0K9">Couleur par défaut</data>
  <data name="Panel.Font.Tooltip.Name" id="0L9">Police du texte par défaut</data>
  <data name="Panel.Font.Tooltip.Size" id="0M9">Taille du texte par défaut</data>
  <data name="Panel.Font.Tooltip.Color" id="0N9">Couleur du texte par défaut</data>
  <data name="Panel.Font.None" id="0O9">Aucun</data>
  <data name="Panel.Gradient.Short.Angle" id="0P9">α</data>
  <data name="Panel.Gradient.Short.Repeat" id="0Q9">n</data>
  <data name="Panel.Gradient.Short.Middle" id="0R9">M</data>
  <data name="Panel.Gradient.Short.Smooth" id="0S9">F</data>
  <data name="Panel.Gradient.Short.HatchAngle" id="0T9">α</data>
  <data name="Panel.Gradient.Short.HatchWidth" id="0U9">e</data>
  <data name="Panel.Gradient.Short.HatchDistance" id="0V9">d</data>
  <data name="Panel.Gradient.Long.Angle" id="00A">Direction du dégradé</data>
  <data name="Panel.Gradient.Long.Repeat" id="01A">Nombre de répétitions</data>
  <data name="Panel.Gradient.Long.Middle" id="02A">Couleur médiane</data>
  <data name="Panel.Gradient.Long.Smooth" id="03A">Distance floue</data>
  <data name="Panel.Gradient.Long.HatchAngle" id="04A">Direction</data>
  <data name="Panel.Gradient.Long.HatchWidth" id="05A">Epaisseur</data>
  <data name="Panel.Gradient.Long.HatchDistance" id="06A">Espacement</data>
  <data name="Panel.Gradient.Long.Hatch1" id="07A">1er trait</data>
  <data name="Panel.Gradient.Long.Hatch2" id="08A">2ème trait</data>
  <data name="Panel.Gradient.Button.Reset" id="09A">R</data>
  <data name="Panel.Gradient.Tooltip.Nothing" id="0AA">Aucune couleur</data>
  <data name="Panel.Gradient.Tooltip.Color1" id="0BA">Couleur 1</data>
  <data name="Panel.Gradient.Tooltip.Color2" id="0CA">Couleur 2</data>
  <data name="Panel.Gradient.Tooltip.Type" id="0DA">Type du remplissage</data>
  <data name="Panel.Gradient.Tooltip.Reset" id="0EA">Reset (valeurs standards)</data>
  <data name="Panel.Gradient.Tooltip.Angle" id="0FA">Direction du dégradé en degrés</data>
  <data name="Panel.Gradient.Tooltip.Hatch1" id="0GA">1er trait</data>
  <data name="Panel.Gradient.Tooltip.Hatch2" id="0HA">2ème trait</data>
  <data name="Panel.Gradient.Tooltip.Repeat" id="0IA">Nombre de répétitions des couleurs</data>
  <data name="Panel.Gradient.Tooltip.Middle" id="0JA">Position de la couleur médiane</data>
  <data name="Panel.Gradient.Tooltip.Smooth" id="0KA">Distance floue vers l&amp;apos;extérieur</data>
  <data name="Panel.Gradient.Tooltip.HatchAngle" id="0LA">Direction en degrés</data>
  <data name="Panel.Gradient.Tooltip.HatchWidth" id="0MA">Epaisseur (zéro si inutilisé)</data>
  <data name="Panel.Gradient.Tooltip.HatchDistance" id="0NA">Espacement</data>
  <data name="Panel.Gradient.Tooltip.Swap" id="0OA">Permute les 2 couleurs</data>
  <data name="Panel.Image.Button.Open" id="04901" mod="1">Importer</data>
  <data name="Panel.Image.Button.Save" id="05901" mod="1">Exporter</data>
  <data name="Panel.Image.Button.Update" id="0PA">Màj</data>
  <data name="Panel.Image.Button.Rotation90" id="0Q901" mod="1">Quart de tour anti-horaire</data>
  <data name="Panel.Image.Button.Rotation180" id="0R901" mod="1">Demi-tour</data>
  <data name="Panel.Image.Button.Rotation270" id="0S901" mod="1">Quart de tour horaire</data>
  <data name="Panel.Image.Button.MirrorX" id="0QA">Miroir horizontal</data>
  <data name="Panel.Image.Button.MirrorY" id="0RA">Miroir vertical</data>
  <data name="Panel.Image.Button.Homo" id="0SA">Conserver les proportions</data>
  <data name="Panel.Image.Button.Inside" id="02901" mod="1">Image incluse au document</data>
  <data name="Panel.Image.Button.Filter" id="0TA">Filtre adoucissant</data>
  <data name="Panel.Image.Combo.Filter.None" id="09A01" mod="1">Pas de filtrage</data>
  <data name="Panel.Image.Combo.Filter.FilterA" id="0AA01" mod="1">Filtrage A</data>
  <data name="Panel.Image.Combo.Filter.FilterB" id="0BA01" mod="1">Filtrage B</data>
  <data name="Panel.Image.Tooltip.Filename" id="0UA">Nom du fichier de l&amp;apos;image</data>
  <data name="Panel.Image.Tooltip.Open" id="0VA">Choix du nom de fichier de l&amp;apos;image à importer</data>
  <data name="Panel.Image.Tooltip.Save" id="06901" mod="1">Exporte l&amp;apos;image dans un fichier sur disque</data>
  <data name="Panel.Image.Tooltip.Update" id="00B">Actualise l&amp;apos;image d&amp;apos;après le fichier sur disque</data>
  <data name="Panel.Image.Dialog.Open.Title" id="01B">Importer une image</data>
  <data name="Panel.Image.Dialog.Save.Title" id="07901" mod="1">Exporter une image</data>
  <data name="Panel.Image.Crop.Title" id="0P901" mod="1">Cadrage</data>
  <data name="Panel.Image.Crop.Tooltip.CropLeft" id="0A901" mod="1">Marge gauche de cadrage en pixels</data>
  <data name="Panel.Image.Crop.Tooltip.CropRight" id="0H901" mod="1">Marge droite de cadrage en pixels</data>
  <data name="Panel.Image.Crop.Tooltip.CropBottom" id="0I901" mod="1">Marge inférieure de cadrage en pixels</data>
  <data name="Panel.Image.Crop.Tooltip.CropTop" id="0J901" mod="1">Marge supérieure de cadrage en pixels</data>
  <data name="Panel.Image.Crop.Tooltip.Zoom" id="0O901" mod="1">Zoom de l&amp;apos;image</data>
  <data name="Panel.Image.Crop.Tooltip.Fill" id="0M901" mod="1">Rempli tout le cadre</data>
  <data name="Panel.Image.Crop.Tooltip.Reset" id="0K901" mod="1">Montre toute l&amp;apos;image</data>
  <data name="Panel.Image.Crop.Button.Fill" id="0L901" mod="1">Remplir</data>
  <data name="Panel.Image.Crop.Button.Reset" id="0N901" mod="1">Tout</data>
  <data name="Panel.Image.Filter.None" id="03A01" mod="1">Mosaïque (pas de filtrage)</data>
  <data name="Panel.Image.Filter.Bilinear" id="04A01" mod="1">Rapide (bilinéaire)</data>
  <data name="Panel.Image.Filter.Bicubic" id="05A01" mod="1">Doux (bicubique)</data>
  <data name="Panel.Image.Filter.Blackman" id="0DA01" mod="1">Normal (Blackman)</data>
  <data name="Panel.Image.Filter.Sinc" id="0EA01" mod="1">Accentué (Sinc)</data>
  <data name="Panel.Image.Filter.Other" id="06A01" mod="1">Filtrage {0}</data>
  <data name="Panel.Justif.Short.MarginH" id="0AB">Mx</data>
  <data name="Panel.Justif.Short.MarginV" id="0BB">My</data>
  <data name="Panel.Justif.Short.OffsetV" id="0CB">Oy</data>
  <data name="Panel.Justif.Long.MarginH" id="0DB">Marges gauche et droite</data>
  <data name="Panel.Justif.Long.MarginV" id="0EB">Marges sup/inf</data>
  <data name="Panel.Justif.Long.OffsetV" id="0FB">Décalage vertical</data>
  <data name="Panel.Justif.Tooltip.MarginH" id="0GB">Marges gauche et droite</data>
  <data name="Panel.Justif.Tooltip.MarginV" id="0HB">Marges supérieure et inférieure</data>
  <data name="Panel.Justif.Tooltip.OffsetV" id="0IB">Décalage vertical</data>
  <data name="Panel.PageName.Label.Name" id="0JB">Nom de la page</data>
  <data name="Panel.PageName.Tooltip.Name" id="0KB">Nom de la page</data>
  <data name="Panel.LayerName.Label.Name" id="0LB">Nom du calque</data>
  <data name="Panel.LayerName.Tooltip.Name" id="0MB">Nom du calque</data>
  <data name="Panel.Line.Short.DashLength" id="0NB">L</data>
  <data name="Panel.Line.Short.DashPen" id="0OB">P</data>
  <data name="Panel.Line.Short.DashGap" id="0PB">V</data>
  <data name="Panel.Line.Long.Width" id="0QB">Epaisseur du trait</data>
  <data name="Panel.Line.Long.Dash1" id="0RB">1er</data>
  <data name="Panel.Line.Long.Dash2" id="0SB">2ème</data>
  <data name="Panel.Line.Long.Dash3" id="0TB">3ème</data>
  <data name="Panel.Line.Long.DashLength" id="0UB">Longueur du motif</data>
  <data name="Panel.Line.Long.DashPen" id="0VB">Longueur du trait</data>
  <data name="Panel.Line.Long.DashGap" id="00C">Longueur du trou</data>
  <data name="Panel.Line.Tooltip.Nothing" id="01C">Aucun trait</data>
  <data name="Panel.Line.Tooltip.Width" id="02C">Epaisseur du trait</data>
  <data name="Panel.Line.Tooltip.Type" id="03C">Type du trait</data>
  <data name="Panel.Line.Tooltip.Dash1" id="04C">1er couple trait/trou</data>
  <data name="Panel.Line.Tooltip.Dash2" id="05C">2ème couple trait/trou</data>
  <data name="Panel.Line.Tooltip.Dash3" id="06C">3ème couple trait/trou</data>
  <data name="Panel.Line.Tooltip.DashLength" id="07C">Longueur du motif de traitillé</data>
  <data name="Panel.Line.Tooltip.DashPen" id="08C">Longueur du trait (zéro si point)</data>
  <data name="Panel.Line.Tooltip.DashGap" id="09C">Longueur du trou (zéro si inutilisé)</data>
  <data name="Panel.ModColor.Short.H" id="0AC">T</data>
  <data name="Panel.ModColor.Short.S" id="0BC">S</data>
  <data name="Panel.ModColor.Short.V" id="0CC">L</data>
  <data name="Panel.ModColor.Short.R" id="0DC">R</data>
  <data name="Panel.ModColor.Short.G" id="0EC">V</data>
  <data name="Panel.ModColor.Short.B" id="0FC">B</data>
  <data name="Panel.ModColor.Short.A" id="0GC">α</data>
  <data name="Panel.ModColor.Short.Negativ" id="0HC">Négatif</data>
  <data name="Panel.ModColor.Short.Draft" id="0IC">C</data>
  <data name="Panel.ModColor.Button.Reset" id="0JC">R</data>
  <data name="Panel.ModColor.Tooltip.H" id="0KC">Teinte</data>
  <data name="Panel.ModColor.Tooltip.S" id="0LC">Saturation</data>
  <data name="Panel.ModColor.Tooltip.V" id="0MC">Luminosité</data>
  <data name="Panel.ModColor.Tooltip.R" id="0NC">Rouge</data>
  <data name="Panel.ModColor.Tooltip.G" id="0OC">Vert</data>
  <data name="Panel.ModColor.Tooltip.B" id="0PC">Bleu</data>
  <data name="Panel.ModColor.Tooltip.A" id="0QC">Alpha (transparence)</data>
  <data name="Panel.ModColor.Tooltip.Negativ" id="0RC">Couleurs inversées</data>
  <data name="Panel.ModColor.Tooltip.Draft" id="0SC">Traits de construction</data>
  <data name="Panel.ModColor.Tooltip.Reset" id="0TC">Reset (valeurs standards)</data>
  <data name="Panel.Name.Tooltip.Title" id="0UC">Nom de l&amp;apos;objet</data>
  <data name="Panel.Regular.Short.Faces" id="0VC">N</data>
  <data name="Panel.Regular.Long.Faces" id="01D">Nombre de côtés</data>
  <data name="Panel.Regular.Label.Deep" id="02D">Renfoncement</data>
  <data name="Panel.Regular.Label.E1" id="0AC01">Extérieur gauche</data>
  <data name="Panel.Regular.Tooltip.E1" id="0EC01">Extérieur gauche (longueur et angle)</data>
  <data name="Panel.Regular.Tooltip.E2" id="0FC01">Extérieur droite (longueur et angle)</data>
  <data name="Panel.Regular.Tooltip.I1" id="0GC01">Intérieur gauche (longueur et angle)</data>
  <data name="Panel.Regular.Tooltip.I2" id="0HC01">Intérieur droite (longueur et angle)</data>
  <data name="Panel.Regular.Sample01" id="0KC01">Triangle équilatéral</data>
  <data name="Panel.Regular.Sample08" id="0LC01">Soleil tournoyant</data>
  <data name="Panel.Regular.Sample09" id="0MC01">Fleur symétrique 1</data>
  <data name="Panel.Regular.Sample10" id="0NC01">Fleur symétrique 2</data>
  <data name="Panel.Regular.Sample11" id="0OC01">Fleur symétrique 3</data>
  <data name="Panel.Regular.Sample12" id="0PC01">Fleur symétrique 4</data>
  <data name="Panel.Regular.Sample13" id="0QC01">Fleur asymétrique 1</data>
  <data name="Panel.Regular.Sample14" id="0RC01">Fleur asymétrique 2</data>
  <data name="Panel.Regular.Sample15" id="0SC01">Trèfle à 4 feuilles</data>
  <data name="Panel.Regular.Sample16" id="03D01">Marguerite</data>
  <data name="Panel.Regular.Sample17" id="04D01">Tournesol</data>
  <data name="Panel.Regular.Sample18" id="05D01">Hélice de bateau</data>
  <data name="Panel.Regular.Sample19" id="06D01">Hélice d&amp;apos;avion</data>
  <data name="Panel.Regular.Sample20" id="07D01">Hélice fantaisie</data>
  <data name="Panel.Regular.Sample21" id="08D01">Forme ajourée</data>
  <data name="Panel.Regular.Custom" id="09D01">Personnalisé</data>
  <data name="Panel.Regular.Sample02" id="0TC01">Carré</data>
  <data name="Panel.Regular.Sample03" id="0UC01">Hexagone</data>
  <data name="Panel.Regular.Sample04" id="0VC01">Octogone</data>
  <data name="Panel.Regular.Sample05" id="00D01">Etoile de David</data>
  <data name="Panel.Regular.Sample06" id="01D01">Scie circulaire</data>
  <data name="Panel.Regular.Sample07" id="02D01">Soleil droit</data>
  <data name="Panel.Regular.Label.E2" id="0BC01">Extérieur droite</data>
  <data name="Panel.Regular.Label.I1" id="0CC01">Intérieur gauche</data>
  <data name="Panel.Regular.Label.I2" id="0DC01">Intérieur droite</data>
  <data name="Panel.Tension.Short.Value" id="09B01">T</data>
  <data name="Panel.Tension.Long.Value" id="0AB01">Tension</data>
  <data name="Panel.Tension.Tooltip.Value" id="0BB01">Tension du trait</data>
  <data name="Panel.Regular.Tooltip.Faces" id="03D">Nombre de côtés</data>
  <data name="Panel.Regular.Tooltip.Deep" id="04D">Renfoncement (longueur et angle)</data>
  <data name="Panel.Surface.Short.Factor" id="05D">R{0}</data>
  <data name="Panel.Surface.Short.Scalar" id="06D">N{0}</data>
  <data name="Panel.Surface.Button.Reset" id="07D">R</data>
  <data name="Panel.Surface.Tooltip.Type" id="08D">Type de la surface 3D</data>
  <data name="Panel.Surface.Tooltip.Reset" id="09D">Reset (valeurs standards)</data>
  <data name="Panel.TextLine.Short.Offset" id="0AD">Oy</data>
  <data name="Panel.TextLine.Short.Add" id="0BD">L</data>
  <data name="Panel.TextLine.Long.Offset" id="0CD">Décalage perpendiculaire</data>
  <data name="Panel.TextLine.Long.Add" id="0DD">Espace intercaractère</data>
  <data name="Panel.TextLine.Tooltip.JustifHLeft" id="0ED">Justification à gauche</data>
  <data name="Panel.TextLine.Tooltip.JustifHCenter" id="0FD">Justification centrée</data>
  <data name="Panel.TextLine.Tooltip.JustifHRight" id="0GD">Justification à droite</data>
  <data name="Panel.TextLine.Tooltip.JustifHStretch" id="0HD">Justification alignée</data>
  <data name="Panel.TextLine.Tooltip.Offset" id="0ID">Décalage perpendiculaire au trait</data>
  <data name="Panel.TextLine.Tooltip.Add" id="0JD">Espace entre les caractères</data>
  <data name="Panel.Volume.Short.Rapport" id="0KD">M</data>
  <data name="Panel.Volume.Short.Left" id="0LD">G</data>
  <data name="Panel.Volume.Short.Right" id="0MD">D</data>
  <data name="Panel.Volume.Long.Rapport" id="0ND">Point milieu</data>
  <data name="Panel.Volume.Long.Left" id="0OD">Angle gauche</data>
  <data name="Panel.Volume.Long.Right" id="0PD">Angle droite</data>
  <data name="Panel.Volume.Tooltip.Type" id="0QD">Type de volume 3D</data>
  <data name="Panel.Volume.Tooltip.Rapport" id="0RD">Position du point milieu</data>
  <data name="Panel.Volume.Tooltip.Left" id="0SD">Angle gauche en degrés</data>
  <data name="Panel.Volume.Tooltip.Right" id="0TD">Angle droite en degrés</data>
  <data name="TextPanel.Filter.Title" id="0UD">Attributs visibles</data>
  <data name="TextPanel.Filter.Tooltip.Usual" id="0VD">Attributs courants</data>
  <data name="TextPanel.Filter.Tooltip.Frequently" id="00E">Attributs fréquents</data>
  <data name="TextPanel.Filter.Tooltip.All" id="01E">Tous les attributs</data>
  <data name="TextPanel.Filter.Tooltip.Paragraph" id="02E">Attributs pour les paragraphes</data>
  <data name="TextPanel.Filter.Tooltip.Character" id="03E">Attributs pour les caractères</data>
  <data name="TextPanel.Font.Title" id="04E">Police</data>
  <data name="TextPanel.Font.Short.Size" id="05E">T</data>
  <data name="TextPanel.Font.Short.Glue" id="06E">E</data>
  <data name="TextPanel.Font.Long.Size" id="07E">%</data>
  <data name="TextPanel.Font.Long.Glue" id="08E">Espacement</data>
  <data name="TextPanel.Font.Tooltip.Face" id="09E">Police de caractères</data>
  <data name="TextPanel.Font.Tooltip.Style" id="0AE">Style de la police</data>
  <data name="TextPanel.Font.Tooltip.Features" id="0BE">Variantes OpenType</data>
  <data name="TextPanel.Font.Tooltip.Size" id="0CE">Taille de la police</data>
  <data name="TextPanel.Font.Tooltip.Glue" id="0DE">Espacement des caractères</data>
  <data name="TextPanel.Generator.Title" id="0EE">Puces et numérotations</data>
  <data name="TextPanel.Generator.Button.Perso" id="0FE">Personnaliser</data>
  <data name="TextPanel.Generator.Tooltip.Perso" id="0GE">Accès aux modifications personnalisées</data>
  <data name="TextPanel.Generator.Tooltip.Generator.Add" id="0HE">Ajouter une ligne à la fin</data>
  <data name="TextPanel.Generator.Tooltip.Generator.Sub" id="0IE">Supprimer la dernière ligne</data>
  <data name="TextPanel.Generator.Tooltip.Justif.None" id="0JE">Pas de tabulateurs</data>
  <data name="TextPanel.Generator.Tooltip.Justif.Left" id="0KE">Tabulateur gauche</data>
  <data name="TextPanel.Generator.Tooltip.Justif.Center" id="0LE">Tabulateur centré</data>
  <data name="TextPanel.Generator.Tooltip.Justif.Right" id="0ME">Tabulateur droite</data>
  <data name="TextPanel.Generator.Tooltip.Continue" id="0NE">La numérotation continue à travers tout le document</data>
  <data name="TextPanel.Generator.Tooltip.SuppressBefore" id="0OE">Cette ligne remplace les précédentes</data>
  <data name="TextPanel.Generator.Tooltip.Color" id="0PE">Couleur du texte</data>
  <data name="TextPanel.Generator.Tooltip.Tab" id="0QE">Position de la puce/numéro</data>
  <data name="TextPanel.Generator.Tooltip.Indent" id="0RE">Position du texte</data>
  <data name="TextPanel.Generator.Tooltip.Size" id="0SE">Taille de la police</data>
  <data name="TextPanel.Generator.Tooltip.Offset" id="0TE">Offset vertical</data>
  <data name="TextPanel.Generator.Tooltip.Fix" id="0UE">Texte fixe</data>
  <data name="TextPanel.Generator.Tooltip.Value" id="0VE">Type de numérotation</data>
  <data name="TextPanel.Generator.Short.Global" id="00F">Global</data>
  <data name="TextPanel.Generator.Short.Tab" id="01F">Puces</data>
  <data name="TextPanel.Generator.Short.Indent" id="02F">Texte</data>
  <data name="TextPanel.Generator.Short.Size" id="03F">Taille</data>
  <data name="TextPanel.Generator.Short.Offset" id="04F">Offset</data>
  <data name="TextPanel.Generator.Label.Tabs" id="05F">Positions des tabulateurs :</data>
  <data name="TextPanel.Generator.Label.Fix" id="06F">Texte</data>
  <data name="TextPanel.Generator.Label.Value" id="07F">Num.</data>
  <data name="TextPanel.Generator.Header.Resume" id="08F">Texte</data>
  <data name="TextPanel.Generator.Header.Prefix" id="09F">Préfix</data>
  <data name="TextPanel.Generator.Header.Value" id="0AF">Num.</data>
  <data name="TextPanel.Generator.Header.Suffix" id="0BF">Suffix</data>
  <data name="TextPanel.Generator.Type.None" id="0CF">Aucune</data>
  <data name="TextPanel.Generator.Type.Bullet1" id="0DF">Puces rondes</data>
  <data name="TextPanel.Generator.Type.Bullet2" id="0EF">Puces carrées</data>
  <data name="TextPanel.Generator.Type.Bullet3" id="0FF">Puces triangulaires</data>
  <data name="TextPanel.Generator.Type.Num1" id="0GF">Numérotation 1.</data>
  <data name="TextPanel.Generator.Type.Num2" id="0HF">Numérotation 1)</data>
  <data name="TextPanel.Generator.Type.Num3" id="0IF">Numérotation A.</data>
  <data name="TextPanel.Generator.Type.Num4" id="0JF">Numérotation a)</data>
  <data name="TextPanel.Generator.Type.Num5" id="0KF">Numérotation 1.1.1.</data>
  <data name="TextPanel.Generator.Type.Custom" id="0LF">Personnalisé</data>
  <data name="TextPanel.Generator.Numerator.None" id="0MF">Aucun</data>
  <data name="TextPanel.Generator.Numerator.Numeric" id="0NF">1, 2...</data>
  <data name="TextPanel.Generator.Numerator.AlphaLower" id="0OF">a, b...</data>
  <data name="TextPanel.Generator.Numerator.AlphaUpper" id="0PF">A, B...</data>
  <data name="TextPanel.Generator.Numerator.RomanLower" id="0QF">i, ii...</data>
  <data name="TextPanel.Generator.Numerator.RomanUpper" id="0RF">I, II...</data>
  <data name="TextPanel.Generator.Text.None" id="0SF">
  </data>
  <data name="TextPanel.Generator.Text.Fix1" id="0TF">.</data>
  <data name="TextPanel.Generator.Text.Fix2" id="0UF">,</data>
  <data name="TextPanel.Generator.Text.Fix3" id="0VF">:</data>
  <data name="TextPanel.Generator.Text.Fix4" id="00G">;</data>
  <data name="TextPanel.Generator.Text.Fix5" id="01G">-</data>
  <data name="TextPanel.Generator.Text.Fix6" id="02G">/</data>
  <data name="TextPanel.Generator.Text.Fix7" id="03G">(</data>
  <data name="TextPanel.Generator.Text.Fix8" id="04G">)</data>
  <data name="TextPanel.Generator.Text.Fix9" id="05G">[</data>
  <data name="TextPanel.Generator.Text.Fix10" id="06G">]</data>
  <data name="TextPanel.Generator.Text.Fix11" id="07G">#</data>
  <data name="TextPanel.Generator.Text.Arial1" id="08G">&lt;font face=&amp;quot;Arial&amp;quot;&gt;●&lt;/font&gt;</data>
  <data name="TextPanel.Generator.Text.Arial2" id="09G">&lt;font face=&amp;quot;Arial&amp;quot;&gt;○&lt;/font&gt;</data>
  <data name="TextPanel.Generator.Text.Arial3" id="0AG">&lt;font face=&amp;quot;Arial&amp;quot;&gt;■&lt;/font&gt;</data>
  <data name="TextPanel.Generator.Text.Arial4" id="0BG">&lt;font face=&amp;quot;Arial&amp;quot;&gt;□&lt;/font&gt;</data>
  <data name="TextPanel.Generator.Text.Arial5" id="0CG">&lt;font face=&amp;quot;Arial&amp;quot;&gt;♦&lt;/font&gt;</data>
  <data name="TextPanel.Generator.Text.Arial6" id="0DG">&lt;font face=&amp;quot;Arial&amp;quot;&gt;◊&lt;/font&gt;</data>
  <data name="TextPanel.Generator.Text.Arial7" id="0EG">&lt;font face=&amp;quot;Arial&amp;quot;&gt;►&lt;/font&gt;</data>
  <data name="TextPanel.Generator.Text.Arial8" id="0FG">&lt;font face=&amp;quot;Arial&amp;quot;&gt;→&lt;/font&gt;</data>
  <data name="TextPanel.Generator.Text.Arial9" id="0GG">&lt;font face=&amp;quot;Arial&amp;quot;&gt;―&lt;/font&gt;</data>
  <data name="TextPanel.Justif.Title" id="0HG">Mise en page</data>
  <data name="TextPanel.Keep.Title" id="0IG">Enchaînements</data>
  <data name="TextPanel.Keep.Tooltip.KeepNext" id="0JG">Lié au paragraphe suivant</data>
  <data name="TextPanel.Keep.Tooltip.KeepPrev" id="0KG">Lié au paragraphe précédent</data>
  <data name="TextPanel.Keep.Tooltip.NextStyle" id="0LG">Style du paragraphe suivant</data>
  <data name="TextPanel.Keep.Short.KeepStart" id="0MG">D</data>
  <data name="TextPanel.Keep.Short.KeepEnd" id="0NG">F</data>
  <data name="TextPanel.Keep.Short.NextStyle" id="0OG">Suivant</data>
  <data name="TextPanel.Keep.Long.KeepStart" id="0PG">Lignes solidaires au début</data>
  <data name="TextPanel.Keep.Long.KeepEnd" id="0QG">Lignes solidaires à la fin</data>
  <data name="TextPanel.Keep.Tooltip.KeepStart" id="0RG">Nombre de lignes solidaires au début du paragraphe</data>
  <data name="TextPanel.Keep.Tooltip.KeepEnd" id="0SG">Nombre de lignes solidaires à la fin du paragraphe</data>
  <data name="TextPanel.Keep.Tooltip.StartMode" id="0TG">Emplacement du début du paragraphe</data>
  <data name="TextPanel.Keep.StartMode.Undefined" id="0UG">&lt;i&gt;Selon le style sous-jacent&lt;/i&gt;</data>
  <data name="TextPanel.Keep.StartMode.Anywhere" id="0VG">N&amp;apos;importe où</data>
  <data name="TextPanel.Keep.StartMode.NewFrame" id="00H">Au début d&amp;apos;un pavé</data>
  <data name="TextPanel.Keep.StartMode.NewPage" id="01H">Au début d&amp;apos;une page</data>
  <data name="TextPanel.Keep.StartMode.NewOddPage" id="02H">Au début d&amp;apos;une page impaire</data>
  <data name="TextPanel.Keep.StartMode.NewEvenPage" id="03H">Au début d&amp;apos;une page paire</data>
  <data name="TextPanel.Leading.Title" id="04H">Interligne</data>
  <data name="TextPanel.Leading.Short.Leading" id="05H">d</data>
  <data name="TextPanel.Leading.Short.GridStep" id="06H">G</data>
  <data name="TextPanel.Leading.Short.GridOffset" id="07H">O</data>
  <data name="TextPanel.Leading.Long.Leading" id="08H">%</data>
  <data name="TextPanel.Leading.Long.GridStep" id="09H">Espacement vertical</data>
  <data name="TextPanel.Leading.Long.GridSubdiv" id="0AH">Subdivisions</data>
  <data name="TextPanel.Leading.Long.GridOffset" id="0BH">Décalage vertical</data>
  <data name="TextPanel.Leading.Tooltip.Leading" id="0CH">Interligne</data>
  <data name="TextPanel.Leading.Tooltip.GridStep" id="0DH">Espacement vertical des lignes magnétiques</data>
  <data name="TextPanel.Leading.Tooltip.GridOffset" id="0EH">Décalage vertical des lignes magnétiques</data>
  <data name="TextPanel.Leading.Tooltip.AlignFirst" id="0FH">Forcer la première ligne du paragraphe sur une ligne magnétique</data>
  <data name="TextPanel.Leading.Tooltip.AlignAll" id="0GH">Forcer toutes les lignes sur les lignes magnétiques</data>
  <data name="TextPanel.Leading.None" id="0HH">Aucun</data>
  <data name="TextPanel.Margins.Title" id="0IH">Retraits</data>
  <data name="TextPanel.Margins.Short.LeftFirst" id="0JH">P</data>
  <data name="TextPanel.Margins.Short.LeftBody" id="0KH">G</data>
  <data name="TextPanel.Margins.Short.Right" id="0LH">D</data>
  <data name="TextPanel.Margins.Short.Level" id="0MH">N</data>
  <data name="TextPanel.Margins.Long.LeftFirst" id="0NH">Marge première ligne</data>
  <data name="TextPanel.Margins.Long.LeftBody" id="0OH">Marge gauche</data>
  <data name="TextPanel.Margins.Long.Right" id="0PH">Marge droite</data>
  <data name="TextPanel.Margins.Long.Level" id="0QH">Niveau d&amp;apos;indentation</data>
  <data name="TextPanel.Margins.Tooltip.Level" id="0RH">Niveau d&amp;apos;indentation (1..9)</data>
  <data name="TextPanel.Numerator.Title" id="0SH">Numérotation</data>
  <data name="TextPanel.Numerator.Label.Start" id="0TH">Numéro initial</data>
  <data name="TextPanel.Numerator.Tooltip.Start" id="0UH">Exemples: 12 ou 15.A.i (laisser vide pour continuer la numérotation)</data>
  <data name="TextPanel.Spaces.Title" id="0VH">Espacements</data>
  <data name="TextPanel.Spaces.Short.Before" id="00I">H</data>
  <data name="TextPanel.Spaces.Short.After" id="01I">B</data>
  <data name="TextPanel.Spaces.Long.Before" id="02I">Espacement avant</data>
  <data name="TextPanel.Spaces.Long.After" id="03I">Espacement après</data>
  <data name="TextPanel.Spaces.Tooltip.Before" id="04I">Espacement avant le paragraphe</data>
  <data name="TextPanel.Spaces.Tooltip.After" id="05I">Espacement après le paragraphe</data>
  <data name="TextPanel.Tabs.Title" id="06I">Tabulateurs</data>
  <data name="TextPanel.Tabs.Table.Pos" id="07I">Position</data>
  <data name="TextPanel.Tabs.Table.Type" id="08I">Type</data>
  <data name="TextPanel.Tabs.Tooltip.New" id="09I">Créer un nouveau tabulateur</data>
  <data name="TextPanel.Tabs.Tooltip.Delete" id="0AI">Supprimer un tabulateur</data>
  <data name="TextPanel.Tabs.Tooltip.Pos" id="0BI">Position du tabulateur</data>
  <data name="TextPanel.Xline.Title" id="0CI">Traits horizontaux</data>
  <data name="TextPanel.Xline.Short.Underline.Thickness" id="0DI">E</data>
  <data name="TextPanel.Xline.Short.Underline.Position" id="0EI">P</data>
  <data name="TextPanel.Xline.Short.Strikeout.Thickness" id="0FI">E</data>
  <data name="TextPanel.Xline.Short.Strikeout.Position" id="0GI">P</data>
  <data name="TextPanel.Xline.Short.Overline.Thickness" id="0HI">E</data>
  <data name="TextPanel.Xline.Short.Overline.Position" id="0II">P</data>
  <data name="TextPanel.Xline.Long.Underline.Thickness" id="0JI">Epaisseur souligné</data>
  <data name="TextPanel.Xline.Long.Underline.Position" id="0KI">Position souligné</data>
  <data name="TextPanel.Xline.Long.Strikeout.Thickness" id="0LI">Epaisseur biffé</data>
  <data name="TextPanel.Xline.Long.Strikeout.Position" id="0MI">Position biffé</data>
  <data name="TextPanel.Xline.Long.Overline.Thickness" id="0NI">Epaisseur surligné</data>
  <data name="TextPanel.Xline.Long.Overline.Position" id="0OI">Position surligné</data>
  <data name="TextPanel.Xline.Tooltip.Underline.Thickness" id="0PI">Epaisseur du souligné</data>
  <data name="TextPanel.Xline.Tooltip.Underline.Position" id="0QI">Position verticale du souligné</data>
  <data name="TextPanel.Xline.Tooltip.Underline.Color" id="0RI">Couleur du souligné</data>
  <data name="TextPanel.Xline.Tooltip.Strikeout.Thickness" id="0SI">Epaisseur du biffé</data>
  <data name="TextPanel.Xline.Tooltip.Strikeout.Position" id="0TI">Position verticale du biffé</data>
  <data name="TextPanel.Xline.Tooltip.Strikeout.Color" id="0UI">Couleur du biffé</data>
  <data name="TextPanel.Xline.Tooltip.Overline.Thickness" id="0VI">Epaisseur du surligné</data>
  <data name="TextPanel.Xline.Tooltip.Overline.Position" id="00J">Position verticale du surligné</data>
  <data name="TextPanel.Xline.Tooltip.Overline.Color" id="01J">Couleur du surligné</data>
  <data name="TextPanel.Xscript.Title" id="02J">Indices et exposants</data>
  <data name="TextPanel.Xscript.Short.Scale" id="03J">E</data>
  <data name="TextPanel.Xscript.Short.Offset" id="04J">D</data>
  <data name="TextPanel.Xscript.Long.Scale" id="05J">Echelle</data>
  <data name="TextPanel.Xscript.Long.Offset" id="06J">Décalage</data>
  <data name="TextPanel.Xscript.Tooltip.Scale" id="07J">Réduction d&amp;apos;échelle</data>
  <data name="TextPanel.Xscript.Tooltip.Offset" id="08J">Décalage vertical</data>
  <data name="TextPanel.Box.Title" id="09J">Cadres</data>
  <data name="TextPanel.Language.Title" id="0AJ">Langue</data>
  <data name="TextPanel.Language.Tooltip.Language" id="0BJ">Langue</data>
  <data name="TextPanel.Language.List.None" id="0CJ">Aucune</data>
  <data name="TextPanel.Language.List.fr" id="0DJ">Français</data>
  <data name="TextPanel.Language.List.de" id="0EJ">Allemand</data>
  <data name="TextPanel.Language.List.en" id="0FJ">Anglais</data>
  <data name="TextPanel.Clear" id="0GJ">Effacer l&amp;apos;attribut</data>
  <data name="TextPanel.Units" id="0HJ">Choix de l&amp;apos;unité</data>
  <data name="Property.Abstract.Name" id="0IJ">Nom</data>
  <data name="Property.Abstract.LineColor" id="0JJ">Couleur trait</data>
  <data name="Property.Abstract.LineMode" id="0KJ">Epaisseur trait</data>
  <data name="Property.Abstract.LineDimension" id="0LJ">Epaisseur supports</data>
  <data name="Property.Abstract.FillGradient" id="0MJ">Couleur intérieure</data>
  <data name="Property.Abstract.Tension" id="07B01">Tension du trait</data>
  <data name="Property.Abstract.FillGradientVT" id="0NJ">Couleur couvercle</data>
  <data name="Property.Abstract.FillGradientVL" id="0OJ">Couleur flanc gauche</data>
  <data name="Property.Abstract.FillGradientVR" id="0PJ">Couleur flanc droit</data>
  <data name="Property.Abstract.Shadow" id="0QJ">Ombre</data>
  <data name="Property.Abstract.PolyClose" id="0RJ">Contour fermé</data>
  <data name="Property.Abstract.Arrow" id="0SJ">Extrémités trait</data>
  <data name="Property.Abstract.DimensionArrow" id="0TJ">Extrémités cote</data>
  <data name="Property.Abstract.Dimension" id="0UJ">Cote</data>
  <data name="Property.Abstract.Corner" id="0VJ">Coins</data>
  <data name="Property.Abstract.Regular" id="00K">Polygone régulier</data>
  <data name="Property.Abstract.Arc" id="01K">Arc</data>
  <data name="Property.Abstract.Surface" id="02K">Surface 2D</data>
  <data name="Property.Abstract.Volume" id="03K">Volume 3D</data>
  <data name="Property.Abstract.BackColor" id="04K">Couleur fond</data>
  <data name="Property.Abstract.TextFont" id="05K">Police</data>
  <data name="Property.Abstract.TextJustif" id="06K">Mise en page (pavé)</data>
  <data name="Property.Abstract.TextLine" id="07K">Mise en page (ligne)</data>
  <data name="Property.Abstract.Image" id="08K">Image</data>
  <data name="Property.Abstract.ModColor" id="09K">Transformation de couleur</data>
  <data name="Property.Arc.Full" id="0AK">Complet</data>
  <data name="Property.Arc.Open" id="0BK">Arc ouvert</data>
  <data name="Property.Arc.Close" id="0CK">Arc fermé</data>
  <data name="Property.Arc.Pie" id="0DK">Camembert</data>
  <data name="Property.Arrow.Right" id="0EK">Rien</data>
  <data name="Property.Arrow.ArrowSimply" id="0FK">Flèche simple</data>
  <data name="Property.Arrow.ArrowFantasy1" id="0GK">Flèche fantaisie</data>
  <data name="Property.Arrow.ArrowCurve1" id="0HK">Flèche courbe 1</data>
  <data name="Property.Arrow.ArrowCurve2" id="0IK">Flèche courbe 2</data>
  <data name="Property.Arrow.ArrowOutline" id="0JK">Flèche filaire</data>
  <data name="Property.Arrow.Slash" id="0KK">Barre oblique</data>
  <data name="Property.Arrow.Dot" id="0LK">Point</data>
  <data name="Property.Arrow.Square" id="0MK">Carré</data>
  <data name="Property.Arrow.Diamond" id="0NK">Losange</data>
  <data name="Property.Close.No" id="0OK">Contour ouvert</data>
  <data name="Property.Close.Yes" id="0PK">Contour fermé</data>
  <data name="Property.Corner.Right" id="0QK">Droit</data>
  <data name="Property.Corner.Round" id="0RK">Arrondi</data>
  <data name="Property.Corner.Bevel" id="0SK">Biseau</data>
  <data name="Property.Corner.Line31" id="0TK">Droites 3.1</data>
  <data name="Property.Corner.Line41" id="0UK">Droites 4.1</data>
  <data name="Property.Corner.Line42" id="0VK">Droites 4.2</data>
  <data name="Property.Corner.Line51" id="00L">Droites 5.1</data>
  <data name="Property.Corner.Line61" id="01L">Droites 6.1</data>
  <data name="Property.Corner.Line62" id="02L">Droites 6.2</data>
  <data name="Property.Corner.Curve21" id="03L">Courbes 2.1</data>
  <data name="Property.Corner.Curve22" id="04L">Courbes 2.2</data>
  <data name="Property.Corner.Curve31" id="05L">Courbes 3.1</data>
  <data name="Property.Corner.Fantasy51" id="06L">Fantaisies 5.1</data>
  <data name="Property.Corner.Fantasy61" id="07L">Fantaisies 6.1</data>
  <data name="Property.Corner.Fantasy62" id="08L">Fantaisies 6.2</data>
  <data name="Property.Dimension.Auto" id="09L">Cote automatique</data>
  <data name="Property.Dimension.Inside" id="0AL">Cote intérieure</data>
  <data name="Property.Dimension.Outside" id="0BL">Cote extérieure</data>
  <data name="Property.Dimension.CenterOrLeft" id="0CL">Texte centré (ou à gauche)</data>
  <data name="Property.Dimension.CenterOrRight" id="0DL">Texte centré (ou à droite)</data>
  <data name="Property.Dimension.Left" id="0EL">Texte à gauche</data>
  <data name="Property.Dimension.Right" id="0FL">Texte à droite</data>
  <data name="Property.Dimension.TextMm" id="0GL"> # mm </data>
  <data name="Property.Dimension.TextIn" id="0IA01"> # in </data>
  <data name="Property.Gradient.None" id="0HL">Uniforme</data>
  <data name="Property.Gradient.Linear" id="0IL">Dégradé linéaire</data>
  <data name="Property.Gradient.Circle" id="0JL">Dégradé concentrique</data>
  <data name="Property.Gradient.Diamond" id="0KL">Dégradé en diamant</data>
  <data name="Property.Gradient.Conic" id="0LL">Dégradé conique</data>
  <data name="Property.Gradient.Hatch" id="0ML">Hachures</data>
  <data name="Property.Gradient.Dots" id="0NL">Points</data>
  <data name="Property.Gradient.Squares" id="0OL">Carrés</data>
  <data name="Property.Justif.JustifHLeft" id="0PL">Justification à gauche</data>
  <data name="Property.Justif.JustifHCenter" id="0QL">Justification centrée</data>
  <data name="Property.Justif.JustifHRight" id="0RL">Justification à droite</data>
  <data name="Property.Justif.JustifHJustif" id="0SL">Justification alignée, sauf dernière ligne</data>
  <data name="Property.Justif.JustifHAll" id="0TL">Justification alignée, y compris dernière ligne</data>
  <data name="Property.Justif.JustifHStretch" id="0UL">Justification alignée</data>
  <data name="Property.Justif.JustifVTop" id="0VL">En haut</data>
  <data name="Property.Justif.JustifVCenter" id="00M">Centré verticalement</data>
  <data name="Property.Justif.JustifVBottom" id="01M">En bas</data>
  <data name="Property.Justif.JustifOLR" id="02M">Orientation normale</data>
  <data name="Property.Justif.JustifOBT" id="03M">Orientation de bas en haut</data>
  <data name="Property.Justif.JustifORL" id="04M">Orientation de droite à gauche</data>
  <data name="Property.Justif.JustifOTB" id="05M">Orientation de haut en bas</data>
  <data name="Property.Leading.Leading08" id="06M">Interligne serré</data>
  <data name="Property.Leading.Leading10" id="07M">Interligne normal</data>
  <data name="Property.Leading.Leading15" id="08M">Interligne étendu</data>
  <data name="Property.Leading.Leading20" id="09M">Interligne double</data>
  <data name="Property.Leading.Leading30" id="0AM">Interligne triple</data>
  <data name="Property.Line.Full" id="0BM">Plein</data>
  <data name="Property.Line.Lines" id="0CM">Traitillé</data>
  <data name="Property.Line.LineDense" id="0DM">Traitillé serré</data>
  <data name="Property.Line.LineExpand" id="0EM">Traitillé étendu</data>
  <data name="Property.Line.Dot" id="0FM">Pointillé</data>
  <data name="Property.Line.LineDot" id="0GM">Trait-pointillé</data>
  <data name="Property.Line.LineDotDot" id="0HM">Trait-point-pointillé</data>
  <data name="Property.Line.Custom" id="0IM">Sur mesure</data>
  <data name="Property.Line.CapRound" id="0JM">Extrémité ronde</data>
  <data name="Property.Line.CapSquare" id="0KM">Extrémité carrée</data>
  <data name="Property.Line.CapButt" id="0LM">Extrémité tronquée</data>
  <data name="Property.Line.JoinRound" id="0MM">Jointure ronde</data>
  <data name="Property.Line.JoinMiter" id="0NM">Jointure pointue</data>
  <data name="Property.Line.JoinBevel" id="0OM">Jointure tronquée</data>
  <data name="Property.Line.Short.Witdh" id="0PM">E = </data>
  <data name="Property.Regular.Norm" id="0QM">Polygone régulier</data>
  <data name="Property.Regular.Star" id="0RM">Etoile</data>
  <data name="Property.Regular.Flower1" id="0IC01">Fleur symétrique</data>
  <data name="Property.Regular.Flower2" id="0JC01">Fleur asymétrique</data>
  <data name="Property.Regular.Short.Faces" id="0SM">N = </data>
  <data name="Property.Tension.Short.Value" id="08B01">T = </data>
  <data name="Property.Surface.ParallelT" id="0TM">Parallélogramme 1</data>
  <data name="Property.Surface.ParallelB" id="0UM">Parallélogramme 2</data>
  <data name="Property.Surface.ParallelL" id="0VM">Parallélogramme 3</data>
  <data name="Property.Surface.ParallelR" id="00N">Parallélogramme 4</data>
  <data name="Property.Surface.TrapezeT" id="01N">Trapèze 1</data>
  <data name="Property.Surface.TrapezeB" id="02N">Trapèze 2</data>
  <data name="Property.Surface.TrapezeL" id="03N">Trapèze 3</data>
  <data name="Property.Surface.TrapezeR" id="04N">Trapèze 4</data>
  <data name="Property.Surface.QuadriL" id="05N">Losange</data>
  <data name="Property.Surface.QuadriP" id="06N">Parallélogramme incliné</data>
  <data name="Property.Surface.QuadriC" id="07N">Cerf-volant</data>
  <data name="Property.Surface.QuadriX" id="08N">Quadrilatère</data>
  <data name="Property.Surface.Grid" id="09N">Grille</data>
  <data name="Property.Surface.Pattern" id="0AN">Damier</data>
  <data name="Property.Surface.Ring" id="0BN">Anneau</data>
  <data name="Property.Surface.SpiralCW" id="0CN">Spirale 1</data>
  <data name="Property.Surface.SpiralCCW" id="0DN">Spirale 2</data>
  <data name="Property.Volume.BoxClose" id="0EN">Boîte fermée</data>
  <data name="Property.Volume.BoxOpen" id="0FN">Boîte ouverte</data>
  <data name="Property.Volume.Pyramid" id="0GN">Pyramide</data>
  <data name="Property.Volume.Cylinder" id="0HN">Cylindre</data>
  <data name="Misc.NoTitle" id="0IN">&lt;i&gt;sans titre&lt;/i&gt;</data>
  <data name="Misc.Copy" id="0JN">Copie</data>
  <data name="Misc.CopyOf" id="0KN">de</data>
  <data name="Misc.Extract" id="0LN">Extrait</data>
  <data name="Misc.ExtractOf" id="0MN">de</data>
  <data name="Sample.Paragraph" id="0NN">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</data>
  <data name="Sample.Character" id="0ON">Lorem ipsum dolor</data>
  <data name="Action.ActionMain" id="0PN">Action</data>
  <data name="Action.ToolSelect" id="0QN">Sélectionner</data>
  <data name="Action.ToolGlobal" id="0RN">Rectangle de sélection</data>
  <data name="Action.ToolShaper" id="0SN">Modeler</data>
  <data name="Action.ToolEdit" id="0TN">Editer</data>
  <data name="Action.ToolZoom" id="0UN">Loupe</data>
  <data name="Action.ToolHand" id="0VN">Main</data>
  <data name="Action.ToolPicker" id="00O">Pipette</data>
  <data name="Action.ToolHotSpot" id="01O">Point chaud</data>
  <data name="Action.ToolLine" id="02O">Segment de ligne</data>
  <data name="Action.ToolFree" id="06B01">Trait à main levée</data>
  <data name="Action.ToolRectangle" id="03O">Rectangle</data>
  <data name="Action.ToolCircle" id="04O">Cercle</data>
  <data name="Action.ToolEllipse" id="05O">Ellipse</data>
  <data name="Action.ToolPoly" id="06O">Polygone quelconque</data>
  <data name="Action.ToolBezier" id="07O">Courbes de Bézier</data>
  <data name="Action.ToolRegular" id="08O">Polygone régulier</data>
  <data name="Action.ToolSurface" id="09O">Surfaces 2D</data>
  <data name="Action.ToolVolume" id="0AO">Volumes 3D</data>
  <data name="Action.ToolTextLine" id="0BO">Ligne de texte</data>
  <data name="Action.ToolTextBox" id="0CO">Pavé de texte</data>
  <data name="Action.ToolArray" id="0DO">Tableau</data>
  <data name="Action.ToolImage" id="0EO">Image bitmap</data>
  <data name="Action.ToolDimension" id="0FO">Cote</data>
  <data name="Action.Apply.Tooltip.StyleParagraph" id="0GO">Appliquer le style de paragraphe {0}</data>
  <data name="Action.Apply.Tooltip.StyleCharacter" id="0HO">Appliquer le style de caractère {0}</data>
  <data name="Action.Apply.Tooltip.Font" id="0IO">Utiliser la police {0}</data>
  <data name="Action.FileMain" id="0JO">Fichier</data>
  <data name="Action.New" id="0KO">Nouveau...</data>
  <data name="Action.Open" id="0LO">Ouvrir...</data>
  <data name="Action.OpenModel" id="0MO">Ouvrir modèle...</data>
  <data name="Action.Close" id="0NO">Fermer</data>
  <data name="Action.CloseAll" id="0OO">Fermer tout</data>
  <data name="Action.Save" id="0PO">Enregistrer</data>
  <data name="Action.SaveAs" id="0QO">Enregistrer sous...</data>
  <data name="Action.SaveModel" id="0RO" mod="1">Enregistrer en tant que modèle...</data>
  <data name="Action.Print" id="0SO">Imprimer...</data>
  <data name="Action.Export" id="0TO">Exporter...</data>
  <data name="Action.LastModels" id="0V901" mod="1">Modèles récents</data>
  <data name="Action.LastFiles" id="0UO">Fichiers récents</data>
  <data name="Action.Quit" id="0VO">Quitter</data>
  <data name="Action.Key" id="00P">Clé...</data>
  <data name="Action.Update" id="01P">Mise à jour...</data>
  <data name="Action.About" id="02P">A propos de...</data>
  <data name="Dialog.File.Statistics" id="0KA01">Format: {0}&lt;br/&gt;Pages/calques: {1}/{2}&lt;br/&gt;Polices/images: {5}/{6}&lt;br/&gt;Objets: {3}/{4}</data>
  <data name="Dialog.OpenImage.Title" id="0PA01">Importer une image</data>
  <data name="Dialog.SaveImage.Title" id="0TA01">Exporter une image</data>
  <data name="Dialog.OpenImage.ActionButtonName" id="0RA01">Importer</data>
  <data name="Dialog.SaveImage.ActionButtonName" id="0SA01">Exporter</data>
  <data name="Action.UndoMain" id="03P">Annuler</data>
  <data name="Action.Undo" id="04P">Annuler</data>
  <data name="Action.UndoRedoList" id="05P">Annuler ou refaire plusieurs actions</data>
  <data name="Action.Redo" id="06P">Refaire</data>
  <data name="Action.Clipboard" id="07P">Presse-papiers</data>
  <data name="Action.Cut" id="08P">Couper</data>
  <data name="Action.Copy" id="09P">Copier</data>
  <data name="Action.Constrain" id="0JA01">Contraintes géométriques (on peut les modifier à la volée&lt;br/&gt;pendant un déplacement avec la touche Espace)</data>
  <data name="Action.Paste" id="0AP">Coller</data>
  <data name="Action.Delete" id="0BP">Supprimer</data>
  <data name="Action.Duplicate" id="0CP">Dupliquer</data>
  <data name="Action.ReplaceMain" id="0DP">Remplacer</data>
  <data name="Action.Replace" id="0EP">Chercher et remplacer...</data>
  <data name="Action.UndoFind" id="0FP">Chercher &amp;quot;{0}&amp;quot;</data>
  <data name="Action.UndoReplace" id="0GP">Remplacer &amp;quot;{0}&amp;quot; par &amp;quot;{1}&amp;quot;</data>
  <data name="Action.DocumentSize" id="0HP">Taille du document</data>
  <data name="Action.ChangeTool" id="0IP">Choix de l&amp;apos;outil &amp;quot;{0}&amp;quot;</data>
  <data name="Action.OutsideArea" id="0JP">Zone hors page</data>
  <data name="Action.SelectMain" id="0KP">Sélection</data>
  <data name="Action.DeselectAll" id="0LP">Tout désélectionner</data>
  <data name="Action.SelectAll" id="0MP">Tout sélectionner</data>
  <data name="Action.SelectInvert" id="0NP">Inverser la sélection</data>
  <data name="Action.SelectName" id="0OP">Sélection par nom &amp;quot;{0}&amp;quot;</data>
  <data name="Action.Selector.Move" id="0PP">Déplacement global</data>
  <data name="Action.Selector.Center" id="0QP">Déplacement du centre de rotation global</data>
  <data name="Action.Selector.Rotate" id="0RP">Rotation globale</data>
  <data name="Action.Selector.Scaler" id="0SP">Mise à l&amp;apos;échelle globale</data>
  <data name="Action.Selector.Stretcher" id="0TP">Déformation globale</data>
  <data name="Action.Selector.Info.Move" id="0UP">dx={0} dy={1}</data>
  <data name="Action.Selector.Info.Scale" id="0VP">échelle x={0}% échelle y={1}%</data>
  <data name="Action.Selector.Info.Center" id="00Q">dx={0} dy={1}</data>
  <data name="Action.Selector.Info.Rotate" id="01Q">angle={0}</data>
  <data name="Action.OrderMain" id="02Q">Ordre</data>
  <data name="Action.OrderUpAll" id="03Q">Premier plan</data>
  <data name="Action.OrderUpOne" id="04Q">En avant</data>
  <data name="Action.OrderDownOne" id="05Q">En arrière</data>
  <data name="Action.OrderDownAll" id="06Q">Arrière-plan</data>
  <data name="Action.OperationMain" id="07Q">Opération</data>
  <data name="Action.MoveMain" id="08Q">Déplacement</data>
  <data name="Action.MoveValueX" id="09Q">Valeur du déplacement horizontal</data>
  <data name="Action.MoveValueY" id="0AQ">Valeur du déplacement vertical</data>
  <data name="Action.MoveLeft" id="0BQ">Déplacement à gauche</data>
  <data name="Action.MoveRight" id="0CQ">Déplacement à droite</data>
  <data name="Action.MoveDown" id="0DQ">Déplacement en bas</data>
  <data name="Action.MoveUp" id="0EQ">Déplacement en haut</data>
  <data name="Action.Move" id="0FQ">Déplacement {0};{1}</data>
  <data name="Action.RotateMain" id="0GQ">Rotation</data>
  <data name="Action.Rotate90" id="0HQ">Quart de tour à gauche</data>
  <data name="Action.Rotate180" id="0IQ">Demi-tour</data>
  <data name="Action.Rotate270" id="0JQ">Quart de tour à droite</data>
  <data name="Action.RotateValue" id="0KQ">Angle de rotation en degrés</data>
  <data name="Action.RotateFreeCCW" id="0LQ">Rotation anti-horaire</data>
  <data name="Action.RotateFreeCW" id="0MQ">Rotation horaire</data>
  <data name="Action.Rotate" id="0NQ">Rotation {0}</data>
  <data name="Action.MirrorMain" id="0OQ">Miroir</data>
  <data name="Action.MirrorH" id="0PQ">Miroir horizontal</data>
  <data name="Action.MirrorV" id="0QQ">Miroir vertical</data>
  <data name="Action.ScaleMain" id="0RQ">Echelle</data>
  <data name="Action.ScaleMul2" id="0SQ">Agrandissement ×2</data>
  <data name="Action.ScaleDiv2" id="0TQ">Réduction ÷2</data>
  <data name="Action.ScaleValue" id="0UQ">Facteur d&amp;apos;agrandissement/réduction</data>
  <data name="Action.ScaleMulFree" id="0VQ">Agrandissement</data>
  <data name="Action.ScaleDivFree" id="00R">Réduction</data>
  <data name="Action.ScaleMul" id="01R">Agrandissement {0}%</data>
  <data name="Action.ScaleDiv" id="02R">Réduction {0}%</data>
  <data name="Action.Reset" id="0HA01">Redresser</data>
  <data name="Action.AlignMain" id="03R">Alignement</data>
  <data name="Action.Align" id="04R">Alignement</data>
  <data name="Action.AlignGrid" id="05R">Alignement sur la grille magnétique</data>
  <data name="Action.AlignLeft" id="06R">Alignement à gauche</data>
  <data name="Action.AlignCenterX" id="07R">Alignement centré horizontalement</data>
  <data name="Action.AlignRight" id="08R">Alignement à droite</data>
  <data name="Action.AlignTop" id="09R">Alignement en haut</data>
  <data name="Action.AlignCenterY" id="0AR">Alignement centré verticalement</data>
  <data name="Action.AlignBottom" id="0BR">Alignement en bas</data>
  <data name="Action.Share" id="0CR">Distribution</data>
  <data name="Action.ShareSpaceX" id="0DR">Distribution espacée horizontalement</data>
  <data name="Action.ShareLeft" id="0ER">Distribution sur la gauche</data>
  <data name="Action.ShareCenterX" id="0FR">Distribution centrée horizontalement</data>
  <data name="Action.ShareRight" id="0GR">Distribution sur la droite</data>
  <data name="Action.ShareSpaceY" id="0HR">Distribution espacée verticalement</data>
  <data name="Action.ShareTop" id="0IR">Distribution sur le haut</data>
  <data name="Action.ShareCenterY" id="0JR">Distribution centrée verticalement</data>
  <data name="Action.ShareBottom" id="0KR">Distribution sur le bas</data>
  <data name="Action.ShareSpace" id="0LR">Distribution espacée</data>
  <data name="Action.Adjust" id="0MR">Ajustement</data>
  <data name="Action.AdjustWidth" id="0NR">Largeurs identiques</data>
  <data name="Action.AdjustHeight" id="0OR">Hauteurs identiques</data>
  <data name="Action.ColorMain" id="0PR">Couleur</data>
  <data name="Action.Color" id="0QR">Couleurs</data>
  <data name="Action.ColorToRgb" id="0RR">Toutes les couleurs en RVB</data>
  <data name="Action.ColorToCmyk" id="0SR">Toutes les couleurs en CMJN</data>
  <data name="Action.ColorToGray" id="0TR">Toutes les couleurs en niveaux de gris</data>
  <data name="Action.ColorValue" id="0UR">Intensité des modifications</data>
  <data name="Action.ColorStrokeDark" id="0VR">Traits plus foncés</data>
  <data name="Action.ColorStrokeLight" id="00S">Traits plus clairs</data>
  <data name="Action.ColorFillDark" id="01S">Surfaces plus foncées</data>
  <data name="Action.ColorFillLight" id="02S">Surfaces plus claires</data>
  <data name="Action.GroupMain" id="03S">Groupe</data>
  <data name="Action.Merge" id="04S">Fusionner dans le groupe</data>
  <data name="Action.Extract" id="05S">Extraire du groupe</data>
  <data name="Action.Group" id="06S">Associer en un groupe</data>
  <data name="Action.Ungroup" id="07S">Dissocier le groupe</data>
  <data name="Action.Inside" id="08S">Entrer dans le groupe</data>
  <data name="Action.Outside" id="09S">Sortir du groupe</data>
  <data name="Action.GeometryMain" id="0AS">Géométrie</data>
  <data name="Action.Combine" id="0BS">Combiner</data>
  <data name="Action.Uncombine" id="0CS">Scinder</data>
  <data name="Action.ToBezier" id="0DS">Convertir en courbes</data>
  <data name="Action.ToPoly" id="0ES">Convertir en droites</data>
  <data name="Action.ToTextBox2" id="0FS">Convertir un ancien texte pour le rendre éditable</data>
  <data name="Action.ToSimplest" id="0GS">Simplifier (debug)</data>
  <data name="Action.Fragment" id="0HS">Fragmenter</data>
  <data name="Action.BooleanMain" id="0IS">Booléen</data>
  <data name="Action.BooleanOr" id="0JS">Union</data>
  <data name="Action.BooleanAnd" id="0KS">Intersection</data>
  <data name="Action.BooleanXor" id="0LS">Exclusion</data>
  <data name="Action.BooleanFrontMinus" id="0MS">Avant moins arrières</data>
  <data name="Action.BooleanBackMinus" id="0NS">Arrière moins avants</data>
  <data name="Action.ShaperHandleAdd" id="0OS">Ajouter le(s) point(s)</data>
  <data name="Action.ShaperHandleSub" id="0PS">Enlever le(s) point(s)</data>
  <data name="Action.ShaperHandleToLine" id="0QS">Droit</data>
  <data name="Action.ShaperHandleSharp" id="0MB01">Anguleux</data>
  <data name="Action.ShaperHandleRound" id="0NB01">Arrondi&lt;br/&gt;</data>
  <data name="Action.ShaperHandleToCurve" id="0RS">Courbe</data>
  <data name="Action.ShaperHandleSym" id="0SS">Symétrique</data>
  <data name="Action.ShaperHandleSmooth" id="0TS">Lisse</data>
  <data name="Action.ShaperHandleDis" id="0US">Anguleux</data>
  <data name="Action.ShaperHandleInline" id="0VS">En ligne</data>
  <data name="Action.ShaperHandleFree" id="00T">Libre</data>
  <data name="Action.ShaperHandleSimply" id="01T">Toujours droit</data>
  <data name="Action.ShaperHandleCorner" id="02T">Selon la propriété de coin</data>
  <data name="Action.ShaperHandleContinue" id="03T">Prolonger le trait</data>
  <data name="Action.Fonts" id="04T">Polices de caractères...</data>
  <data name="Action.Glyphs" id="05T">Caractères spéciaux...</data>
  <data name="Action.HideSel" id="06T">Cacher la sélection</data>
  <data name="Action.HideRest" id="07T">Cacher le reste</data>
  <data name="Action.HideCancel" id="08T">Montrer tout</data>
  <data name="Action.HideHalf" id="09T">Mode estompé</data>
  <data name="Action.PageChange" id="0AT">Changer de page</data>
  <data name="Action.PageNew" id="0BT">Nouvelle page</data>
  <data name="Action.PageNewLong" id="0CT">Nouvelle page &lt;b&gt;après&lt;/b&gt; la page courante</data>
  <data name="Action.PageDuplicate" id="0DT">Dupliquer la page</data>
  <data name="Action.PageDelete" id="0ET">Supprimer la page</data>
  <data name="Action.PageSwap" id="0FT">Permuter deux pages</data>
  <data name="Action.PageName" id="0GT">Renommer la page</data>
  <data name="Action.PageStack" id="0HT">Structure de la page...</data>
  <data name="Action.PageUp" id="0IT">Reculer la page</data>
  <data name="Action.PageDown" id="0JT">Avancer la page</data>
  <data name="Action.PagePrev" id="0KT">Page précédente</data>
  <data name="Action.PageMenu" id="0LT">Choix d&amp;apos;une page</data>
  <data name="Action.PageNext" id="0MT">Page suivante</data>
  <data name="Action.PageChangeStatus" id="0NT">Changer l&amp;apos;état de la page</data>
  <data name="Action.LayerChange" id="0OT">Changer de calque</data>
  <data name="Action.LayerNew" id="0PT">Nouveau calque</data>
  <data name="Action.LayerNewLong" id="0QT">Nouveau calque &lt;b&gt;dessus&lt;/b&gt; le calque courant</data>
  <data name="Action.LayerNewSel" id="0RT">Sélection dans un nouveau calque</data>
  <data name="Action.LayerDuplicate" id="0ST">Dupliquer le calque</data>
  <data name="Action.LayerDelete" id="0TT">Supprimer le calque</data>
  <data name="Action.LayerMerge" id="0UT">Fusionner les calques</data>
  <data name="Action.LayerMergeUp" id="0VT">Fusionne avec le calque dessus</data>
  <data name="Action.LayerMergeDown" id="00U">Fusionne avec le calque dessous</data>
  <data name="Action.LayerSwap" id="01U">Permuter deux calques</data>
  <data name="Action.LayerName" id="02U">Renommer le calque</data>
  <data name="Action.LayerUp" id="03U">Monter le calque</data>
  <data name="Action.LayerDown" id="04U">Descendre le calque</data>
  <data name="Action.LayerNext" id="05U">Calque suivant</data>
  <data name="Action.LayerMenu" id="06U">Choix d&amp;apos;un calque</data>
  <data name="Action.LayerPrev" id="07U">Calque précédent</data>
  <data name="Action.LayerChangeShowOne" id="08U">Changer la visibilité du calque</data>
  <data name="Action.LayerChangeShowAll" id="09U">Changer la visibilité des calques</data>
  <data name="Action.LayerChangePrint" id="0AU">Changer le mode d&amp;apos;impression du calque</data>
  <data name="Action.LayerChangeMagnet" id="0BU">Changer l&amp;apos;état du calque</data>
  <data name="Action.AggregateUse" id="0CU">Utiliser le style &amp;quot;{0}&amp;quot;</data>
  <data name="Action.AggregateNewEmpty" id="0DU">Nouveau style vide</data>
  <data name="Action.AggregateNew3" id="0EU">Nouveau style pour trait et couleurs</data>
  <data name="Action.AggregateNewAll" id="0FU">Nouveau style pour tout</data>
  <data name="Action.AggregateNewParagraph" id="0GU">Nouveau style de paragraphe</data>
  <data name="Action.AggregateNewCharacter" id="0HU">Nouveau style de caractère</data>
  <data name="Action.AggregateDuplicate" id="0IU">Dupliquer un style</data>
  <data name="Action.AggregateUp" id="0JU">Style plus haut</data>
  <data name="Action.AggregateDown" id="0KU">Style plus bas</data>
  <data name="Action.AggregateDelete" id="0LU">Supprimer un style</data>
  <data name="Action.AggregateSwap" id="0MU">Permuter deux styles</data>
  <data name="Action.AggregateChange" id="0NU">Changement du style</data>
  <data name="Action.AggregateFree" id="0OU">Libèrer le style</data>
  <data name="Action.AggregateStyleNew" id="0PU">Créer un attribut pour le style</data>
  <data name="Action.AggregateStyleDelete" id="0QU">Supprimer un attribut du style</data>
  <data name="Action.AggregateChildrenNew" id="0RU">Ajouter un style de base</data>
  <data name="Action.AggregateChildrenDelete" id="0SU">Supprimer le style de base</data>
  <data name="Action.GuideNewH" id="0TU">Nouveau repère horizontal</data>
  <data name="Action.GuideNewV" id="0UU">Nouveau repère vertical</data>
  <data name="Action.GuideDuplicate" id="0VU">Dupliquer le repère</data>
  <data name="Action.GuideXfer" id="00V">Repère global &amp;lt;-&amp;gt; page courante</data>
  <data name="Action.GuideUp" id="01V">Repère avant</data>
  <data name="Action.GuideDown" id="02V">Repère après</data>
  <data name="Action.GuideDelete" id="03V">Supprimer le repère</data>
  <data name="Action.GuideSelect" id="04V">Sélectionner un repère</data>
  <data name="Action.GuideChangeType" id="05V">Changer le type d&amp;apos;un repère</data>
  <data name="Action.GuideChangePosition" id="06V">Changer la position d&amp;apos;un repère</data>
  <data name="Action.PropertyChange" id="07V">Changement de l&amp;apos;attribut &amp;quot;{0}&amp;quot;</data>
  <data name="Action.PickerProperty" id="08V">Style selon la pipette</data>
  <data name="Action.ObjectCreate" id="09V">Création d&amp;apos;un objet &amp;quot;{0}&amp;quot;</data>
  <data name="Action.Select" id="0AV">Sélection</data>
  <data name="Action.Shaper" id="0BV">Modeler</data>
  <data name="Action.HandleMove" id="0CV">Déplacement d&amp;apos;un sommet</data>
  <data name="Action.GuideMove" id="0DV">Déplacement d&amp;apos;un repère</data>
  <data name="Action.GuideCreateAndMove" id="0EV">Création puis déplacement d&amp;apos;un repère</data>
  <data name="Action.SelectGlobal" id="0FV">Sélection rectangulaire</data>
  <data name="Action.SelectObject" id="0GV">Sélection d&amp;apos;un objet</data>
  <data name="Action.SelectHandle" id="0HV">Sélection d&amp;apos;un sommet</data>
  <data name="Action.MoveObject" id="0IV">Déplacement d&amp;apos;un objet</data>
  <data name="Action.DuplicateAndMove" id="0JV">Dupliquer puis déplacer</data>
  <data name="Action.SelectAndMove" id="0KV">Sélection puis déplacement d&amp;apos;un objet</data>
  <data name="Action.SelectGlobalAdd" id="0LV">Ajout d&amp;apos;une sélection rectangulaire</data>
  <data name="Action.SelectObjectAdd" id="0MV">Objet ajouté à la sélection</data>
  <data name="Action.SelectObjectSub" id="0NV">Objet enlevé à la sélection</data>
  <data name="Action.SelectHandleAdd" id="0OV">Sommet ajouté à la sélection</data>
  <data name="Action.SelectHandleSub" id="0PV">Sommet enlevé à la sélection</data>
  <data name="Action.Edit" id="0QV">Edition</data>
  <data name="Action.Picker" id="0RV">Pipette</data>
  <data name="Action.SelectMode" id="0SV">Mode de sélection</data>
  <data name="Action.StretchType" id="0TV">Type de déformation</data>
  <data name="Action.SurfaceReset" id="0UV">Réinitialisation de la surface</data>
  <data name="Action.ZoomMain" id="0VV">Zoom</data>
  <data name="Action.ZoomMin" id="00001">Zoom minimal</data>
  <data name="Action.ZoomPage" id="01001">Zoom pleine page</data>
  <data name="Action.ZoomPageWidth" id="02001">Zoom largeur page</data>
  <data name="Action.ZoomDefault" id="03001">Zoom 100%</data>
  <data name="Action.ZoomSel" id="04001">Zoom sélection</data>
  <data name="Action.ZoomSelWidth" id="05001">Zoom largeur sélection</data>
  <data name="Action.ZoomPrev" id="06001">Zoom précédent</data>
  <data name="Action.ZoomSub" id="07001">Réduction</data>
  <data name="Action.ZoomAdd" id="08001">Agrandissement</data>
  <data name="Action.ZoomValue" id="09001">Facteur de zoom</data>
  <data name="Action.ZoomMenu" id="0A001">Choix du zoom</data>
  <data name="Action.ViewMain" id="0B001">Vue</data>
  <data name="Action.Grid" id="0C001">Grille magnétique</data>
  <data name="Action.TextGrid" id="0D001">Montrer les lignes magnétiques pour le texte</data>
  <data name="Action.TextShowControlCharacters" id="0E001">Afficher les caractères spéciaux</data>
  <data name="Action.TextFontFilter" id="0F001">Seulement les caractères fréquement utilisés</data>
  <data name="Action.TextInsertQuad" id="0G001">Insérer un espace insécable</data>
  <data name="Action.TextInsertNewFrame" id="0H001">Insérer un saut d&amp;apos;objet</data>
  <data name="Action.TextInsertNewPage" id="0I001">Insérer un saut de page</data>
  <data name="Action.Preview" id="0J001">Comme imprimé</data>
  <data name="Action.Magnet" id="0K001" mod="1">Objets magnétiques (la touche Tab change le point&lt;br/&gt;d&amp;apos;accroche lors d&amp;apos;un déplacement global)</data>
  <data name="Action.MagnetLayer" id="0L001">Les objets du calque sont magnétiques</data>
  <data name="Action.Rulers" id="0M001">Règles graduées</data>
  <data name="Action.Labels" id="0N001">Affiche les noms des objets</data>
  <data name="Action.Aggregates" id="0O001">Affiche les noms des styles</data>
  <data name="Action.Settings" id="0P001">Réglages...</data>
  <data name="Action.Infos" id="0Q001">Informations...</data>
  <data name="Action.LabelProperties" id="0R001">Attributs détaillés</data>
  <data name="Action.TextStylesMain" id="0S001">Styles</data>
  <data name="Action.FontMain" id="0T001">Caractère</data>
  <data name="Action.FontFace" id="0U001">Nom de la police</data>
  <data name="Action.FontStyle" id="0V001">Style de la police</data>
  <data name="Action.FontFeatures" id="00101">Variantes OpenType</data>
  <data name="Action.FontSize" id="01101">Taille de la police</data>
  <data name="Action.FontSizePlus" id="02101">Police plus grande</data>
  <data name="Action.FontSizeMinus" id="03101">Police plus petite</data>
  <data name="Action.FontBold" id="04101">Gras</data>
  <data name="Action.FontItalic" id="05101">Italique</data>
  <data name="Action.FontInvertBold" id="06101">Inverser le gras</data>
  <data name="Action.FontInvertItalic" id="07101">Inverser l&amp;apos;italique</data>
  <data name="Action.FontUnderline" id="08101">Souligné</data>
  <data name="Action.FontOverline" id="09101">Surligné</data>
  <data name="Action.FontStrikeout" id="0A101">Biffé</data>
  <data name="Action.FontFrame" id="0B101">Bordure</data>
  <data name="Action.FontSubscript" id="0C101">Indice</data>
  <data name="Action.FontSuperscript" id="0D101">Exposant</data>
  <data name="Action.FontUserX" id="0E101">Style utilisateur X</data>
  <data name="Action.FontUserY" id="0F101">Style utilisateur Y</data>
  <data name="Action.FontUserZ" id="0G101">Style utilisateur Z</data>
  <data name="Action.FontColor" id="0H101">Couleur de la police</data>
  <data name="Action.FontDefault" id="0I101">Auto</data>
  <data name="Action.FontClear" id="0J101">Effacer tous les attributs de caractère</data>
  <data name="Action.ParagraphMain" id="0K101">Paragraphe</data>
  <data name="Action.ParagraphJustif" id="0L101">Modifier la justification</data>
  <data name="Action.ParagraphBulletRound" id="0M101">Puces</data>
  <data name="Action.ParagraphBulletNumeric" id="0N101">Numérotation 1..</data>
  <data name="Action.ParagraphBulletAlpha" id="0O101">Numérotation A..</data>
  <data name="Action.ParagraphIndent" id="0P101">Modifier le retrait</data>
  <data name="Action.ParagraphIndentPlus" id="0Q101">Augmenter le retrait</data>
  <data name="Action.ParagraphIndentMinus" id="0R101">Diminuer le retrait</data>
  <data name="Action.ParagraphAlignLeft" id="0S101">Aligné à gauche</data>
  <data name="Action.ParagraphAlignCenter" id="0T101">Centré</data>
  <data name="Action.ParagraphAlignRight" id="0U101">Aligné à droite</data>
  <data name="Action.ParagraphAlignJustif" id="0V101">Justifié (sans la dernière ligne)</data>
  <data name="Action.ParagraphAlignAll" id="00201">Justifié (avec la dernière ligne)</data>
  <data name="Action.ParagraphHyphen" id="01201">Césures dans les mots</data>
  <data name="Action.ParagraphLeading" id="02201">Modifier l&amp;apos;interligne</data>
  <data name="Action.ParagraphLeadingMinus" id="03201">Diminuer l&amp;apos;interligne</data>
  <data name="Action.ParagraphLeadingPlus" id="04201">Augmenter l&amp;apos;interligne</data>
  <data name="Action.ParagraphGenerator" id="05201">Modifier les puces/numérotations</data>
  <data name="Action.ParagraphClear" id="06201">Effacer tous les attributs de paragraphe</data>
  <data name="Action.Text.Insert" id="07201">Insertion</data>
  <data name="Action.Text.Edit.InsertText" id="08201">Insertion de &amp;quot;{0}&amp;quot;</data>
  <data name="Action.Text.Edit.DeleteText" id="09201">Suppression de &amp;quot;{0}&amp;quot;</data>
  <data name="Action.Text.Edit.ChangeText" id="0A201">Modification de caractères</data>
  <data name="Action.Text.Edit.MoveCursor" id="0B201">Déplacement du curseur</data>
  <data name="Action.Text.Edit.DefineSelection" id="0C201">Sélection de caractères</data>
  <data name="Action.Text.Edit.ClearSelection" id="0D201">Désélection de caractères</data>
  <data name="Action.Text.FlowChanged" id="0E201">Modification du chaînage</data>
  <data name="Action.Text.Ruler.Drag" id="0F201">Tirer avec la souris pour créer un repère</data>
  <data name="Action.Text.Ruler.HandleLeftFirst" id="0G201">Marge gauche de première ligne</data>
  <data name="Action.Text.Ruler.HandleLeftBody" id="0H201">Marge gauche de corps de texte</data>
  <data name="Action.Text.Ruler.HandleFirstBody" id="0I201">Marge gauche</data>
  <data name="Action.Text.Ruler.HandleRight" id="0J201">Marge droite</data>
  <data name="Action.Text.Ruler.HandleMoveLeft" id="0K201">{0}, largeur={1}</data>
  <data name="Action.Text.Ruler.HandleMoveRight" id="0L201">{0} ({1}), largeur={2}</data>
  <data name="Action.Text.Ruler.TabChoice" id="0M201">Choix du tabulateur</data>
  <data name="Action.Text.Ruler.TabLeft" id="0N201">Tabulateur normal</data>
  <data name="Action.Text.Ruler.TabRight" id="0O201">Tabulateur droite</data>
  <data name="Action.Text.Ruler.TabCenter" id="0P201">Tabulateur centré</data>
  <data name="Action.Text.Ruler.TabIndent" id="0Q201">Indentateur</data>
  <data name="Action.Text.Ruler.TabDecimal" id="0R201">Tabulateur sur {0} ({1})</data>
  <data name="Action.Text.Ruler.TabDecimalMath" id="0S201">Tabulateur sur symbole mathématique</data>
  <data name="Action.Text.Ruler.TabDecimalBus" id="0T201">Tabulateur sur symbole commercial</data>
  <data name="Action.Text.Ruler.TabDecimalSign" id="0U201">Tabulateur sur caractère spécial</data>
  <data name="Action.Text.Ruler.TabDecimalPar" id="0V201">Tabulateur sur parenthèse</data>
  <data name="Action.Text.Ruler.TabZombie" id="00301">Tabulateur supprimé</data>
  <data name="Action.Text.Ruler.TabMerge" id="01301">Fusionner les tabulateurs</data>
  <data name="Action.Text.Ruler.TabCreate" id="02301">Cliquez pour poser un tabulateur</data>
  <data name="Action.Text.Glyphs.Insert" id="03301">Insertion caractère spécial</data>
  <data name="Action.Text.Glyphs.Alternate" id="04301">Caractère alternatif</data>
  <data name="Action.Text.Tab.Create" id="05301">Créer un tabulateur</data>
  <data name="Action.Text.Tab.Modify" id="06301">Modifier un tabulateur</data>
  <data name="Action.Text.Tab.Delete" id="07301">Supprimer un tabulateur</data>
  <data name="Text.Features_aalt" id="08301">Access All Alternates</data>
  <data name="Text.Features_abvf" id="09301">Above-Base Forms</data>
  <data name="Text.Features_abvm" id="0A301">Above-Base Mark Positioning</data>
  <data name="Text.Features_abvs" id="0B301">Above-Base Substitutions</data>
  <data name="Text.Features_afrc" id="0C301">Alternative Fractions</data>
  <data name="Text.Features_akhn" id="0D301">Akhands</data>
  <data name="Text.Features_alts" id="0E301">Alternate Forms</data>
  <data name="Text.Features_blwf" id="0F301">Below-Base Forms</data>
  <data name="Text.Features_blwm" id="0G301">Below-Base Mark Positioning</data>
  <data name="Text.Features_blws" id="0H301">Below-Base Substitutions</data>
  <data name="Text.Features_c2pc" id="0I301">Petite Capitals From Capitals</data>
  <data name="Text.Features_c2sc" id="0J301">Small Capitals From Capitals</data>
  <data name="Text.Features_calt" id="0K301">Contextual Alternates</data>
  <data name="Text.Features_case" id="0L301">Case-Sensitive Forms</data>
  <data name="Text.Features_ccmp" id="0M301">Glyph Composition/Decomposition</data>
  <data name="Text.Features_clig" id="0N301">Contextual Ligatures</data>
  <data name="Text.Features_cjct" id="0O301">Conjunct Forms</data>
  <data name="Text.Features_cpsp" id="0P301">Capital Spacing</data>
  <data name="Text.Features_cswh" id="0Q301">Contextual Swash</data>
  <data name="Text.Features_curs" id="0R301">Cursive Positioning</data>
  <data name="Text.Features_dflt" id="0S301">Default Processing</data>
  <data name="Text.Features_dist" id="0T301">Distances</data>
  <data name="Text.Features_dlig" id="0U301">Discretionary Ligatures</data>
  <data name="Text.Features_dnom" id="0V301">Denominators</data>
  <data name="Text.Features_dpng" id="00401">Diphthongs (æ, œ)</data>
  <data name="Text.Features_expt" id="01401">Expert Forms</data>
  <data name="Text.Features_falt" id="02401">Final glyph Alternates</data>
  <data name="Text.Features_fin2" id="03401">Terminal Forms #2</data>
  <data name="Text.Features_fin3" id="04401">Terminal Forms #3</data>
  <data name="Text.Features_fina" id="05401">Terminal Forms</data>
  <data name="Text.Features_frac" id="06401">Fractions</data>
  <data name="Text.Features_fwid" id="07401">Full Width</data>
  <data name="Text.Features_half" id="08401">Half Forms</data>
  <data name="Text.Features_haln" id="09401">Halant Forms</data>
  <data name="Text.Features_halt" id="0A401">Alternate Half Width</data>
  <data name="Text.Features_hist" id="0B401">Historical Forms</data>
  <data name="Text.Features_hkna" id="0C401">Horizontal Kana Alternates</data>
  <data name="Text.Features_hlig" id="0D401">Historical Ligatures</data>
  <data name="Text.Features_hngl" id="0E401">Hangul</data>
  <data name="Text.Features_hojo" id="0F401">Hojo Kanji Forms (JIS x 212-1990 Kanji Forms)</data>
  <data name="Text.Features_hwid" id="0G401">Half Width</data>
  <data name="Text.Features_init" id="0H401">Initial Forms</data>
  <data name="Text.Features_isol" id="0I401">Isolated Forms</data>
  <data name="Text.Features_ital" id="0J401">Italics</data>
  <data name="Text.Features_jajp" id="0K401">Japanese Forms</data>
  <data name="Text.Features_jalt" id="0L401">Justification Alternatives</data>
  <data name="Text.Features_jp78" id="0M401">JIS78 Forms</data>
  <data name="Text.Features_jp83" id="0N401">JIS83 Forms</data>
  <data name="Text.Features_jp90" id="0O401">JIS90 Forms</data>
  <data name="Text.Features_jp04" id="0P401">JIS2004 Forms</data>
  <data name="Text.Features_kern" id="0Q401">Kerning</data>
  <data name="Text.Features_lfbd" id="0R401">Left Bounds</data>
  <data name="Text.Features_liga" id="0S401">Standard Ligatures</data>
  <data name="Text.Features_ljmo" id="0T401">Leading Jamo Forms</data>
  <data name="Text.Features_lnum" id="0U401">Lining Figures</data>
  <data name="Text.Features_locl" id="0V401">Localized Forms</data>
  <data name="Text.Features_mark" id="00501">Mark Positioning</data>
  <data name="Text.Features_med2" id="01501">Medial Forms #2</data>
  <data name="Text.Features_medi" id="02501">Medial Forms</data>
  <data name="Text.Features_mgrk" id="03501">Mathematical Greek</data>
  <data name="Text.Features_mkmk" id="04501">Mark to Mark Positioning</data>
  <data name="Text.Features_mset" id="05501">Mark Positioning via Substitution</data>
  <data name="Text.Features_nalt" id="06501">Alternate Annotation Forms</data>
  <data name="Text.Features_nlck" id="07501">NLC Kanji Forms</data>
  <data name="Text.Features_nukt" id="08501">Nukta Forms</data>
  <data name="Text.Features_numr" id="09501">Numerators</data>
  <data name="Text.Features_onum" id="0A501">Old Style Figures</data>
  <data name="Text.Features_opbd" id="0B501">Optical Bounds</data>
  <data name="Text.Features_ordn" id="0C501">Ordinals</data>
  <data name="Text.Features_ornm" id="0D501">Ornaments</data>
  <data name="Text.Features_palt" id="0E501">Proportional Alternate Width</data>
  <data name="Text.Features_pcap" id="0F501">Petite Capitals</data>
  <data name="Text.Features_pnum" id="0G501">Proportional Figures</data>
  <data name="Text.Features_pref" id="0H501">Pre-base Forms</data>
  <data name="Text.Features_pres" id="0I501">Pre-base Substitutions</data>
  <data name="Text.Features_pstf" id="0J501">Post-base Forms</data>
  <data name="Text.Features_psts" id="0K501">Post-base Substitutions</data>
  <data name="Text.Features_pwid" id="0L501">Proportional Widths</data>
  <data name="Text.Features_qwid" id="0M501">Quarter Widths</data>
  <data name="Text.Features_rand" id="0N501">Randomize</data>
  <data name="Text.Features_rkrf" id="0O501">Rakar Forms</data>
  <data name="Text.Features_rlig" id="0P501">Required Ligatures</data>
  <data name="Text.Features_rphf" id="0Q501">Reph Form</data>
  <data name="Text.Features_rtbd" id="0R501">Right Bounds</data>
  <data name="Text.Features_rtla" id="0S501">Right-To-Left Alternates</data>
  <data name="Text.Features_ruby" id="0T501">Ruby Notation Forms</data>
  <data name="Text.Features_salt" id="0U501">Stylistic Alternates</data>
  <data name="Text.Features_sinf" id="0V501">Scientific Inferiors</data>
  <data name="Text.Features_size" id="00601">Optical Size</data>
  <data name="Text.Features_smcp" id="01601">Small Capitals</data>
  <data name="Text.Features_smpl" id="02601">Simplified Forms</data>
  <data name="Text.Features_ss01" id="03601">Sylistic Set 1</data>
  <data name="Text.Features_ss02" id="04601">Sylistic Set 2</data>
  <data name="Text.Features_ss03" id="05601">Sylistic Set 3</data>
  <data name="Text.Features_ss04" id="06601">Sylistic Set 4</data>
  <data name="Text.Features_ss05" id="07601">Sylistic Set 5</data>
  <data name="Text.Features_ss06" id="08601">Sylistic Set 6</data>
  <data name="Text.Features_ss07" id="09601">Sylistic Set 7</data>
  <data name="Text.Features_ss08" id="0A601">Sylistic Set 8</data>
  <data name="Text.Features_ss09" id="0B601">Sylistic Set 9</data>
  <data name="Text.Features_ss10" id="0C601">Sylistic Set 10</data>
  <data name="Text.Features_ss11" id="0D601">Sylistic Set 11</data>
  <data name="Text.Features_ss12" id="0E601">Sylistic Set 12</data>
  <data name="Text.Features_ss13" id="0F601">Sylistic Set 13</data>
  <data name="Text.Features_ss14" id="0G601">Sylistic Set 14</data>
  <data name="Text.Features_ss15" id="0H601">Sylistic Set 15</data>
  <data name="Text.Features_ss16" id="0I601">Sylistic Set 16</data>
  <data name="Text.Features_ss17" id="0J601">Sylistic Set 17</data>
  <data name="Text.Features_ss18" id="0K601">Sylistic Set 18</data>
  <data name="Text.Features_ss19" id="0L601">Sylistic Set 19</data>
  <data name="Text.Features_ss20" id="0M601">Sylistic Set 20</data>
  <data name="Text.Features_subs" id="0N601">Subscript</data>
  <data name="Text.Features_sups" id="0O601">Superscript</data>
  <data name="Text.Features_swsh" id="0P601">Swash</data>
  <data name="Text.Features_titl" id="0Q601">Titling</data>
  <data name="Text.Features_tjmo" id="0R601">Trailing Jamo Forms</data>
  <data name="Text.Features_tnam" id="0S601">Traditional Name Forms</data>
  <data name="Text.Features_tnum" id="0T601">Tabular Figures</data>
  <data name="Text.Features_trad" id="0U601">Traditional Forms</data>
  <data name="Text.Features_twid" id="0V601">Third Widths</data>
  <data name="Text.Features_unic" id="00701">Unicase</data>
  <data name="Text.Features_valt" id="01701">Alternate Vertical Metrics</data>
  <data name="Text.Features_vatu" id="02701">Vattu Variants</data>
  <data name="Text.Features_vert" id="03701">Vertical Writing</data>
  <data name="Text.Features_vhal" id="04701">Alternate Vertical Half Metrics</data>
  <data name="Text.Features_vjmo" id="05701">Vowel Jamo Forms</data>
  <data name="Text.Features_vkna" id="06701">Vertical Kana Alternates</data>
  <data name="Text.Features_vkrn" id="07701">Vertical Kerning</data>
  <data name="Text.Features_vpal" id="08701">Proportional Alternate Vertical Metrics</data>
  <data name="Text.Features_vrt2" id="09701">Vertical Rotation</data>
  <data name="Text.Features_zero" id="0A701">Slashed Zero</data>
  <data name="Text.FeaturesUnknow" id="0B701">Variante &amp;quot;{0}&amp;quot;</data>
  <data name="Statistic.Summary" id="0C701">{0}Résumé{1}</data>
  <data name="Statistic.Filename" id="0D701">{0}Nom complet: {1}</data>
  <data name="Statistic.Size" id="0E701">{0}Dimensions: {1}x{2}</data>
  <data name="Statistic.Pages" id="0F701">{0}Nombre de pages: {1}</data>
  <data name="Statistic.Layers" id="0G701">{0}Nombre de calques: {1}</data>
  <data name="Statistic.Objects" id="0H701">{0}Nombre d&amp;apos;objets: {1}</data>
  <data name="Statistic.Gradients" id="0I701">{0}Objets dégradés ou transparents: {1}</data>
  <data name="Statistic.Fonts" id="0J701">{0}Polices utilisées{1}</data>
  <data name="Statistic.Images" id="0K701">{0}Images utilisées{1}</data>
  <data name="Statistic.None" id="0L701">&lt;i&gt;Aucune&lt;/i&gt;</data>
  <data name="Menu.Zoom.Page" id="0M701">pleine page</data>
  <data name="Menu.Zoom.Current" id="0N701">actuel</data>
  <data name="Page.ShortName.Default" id="0O701">{0}</data>
  <data name="Page.ShortName.Model" id="0P701">M{0}</data>
  <data name="Layer.PositionName.Unique" id="0Q701">Unique</data>
  <data name="Layer.PositionName.Front" id="0R701">Dessus</data>
  <data name="Layer.PositionName.Middle" id="0S701">Fond+{0}</data>
  <data name="Layer.PositionName.Back" id="0T701">Fond</data>
  <data name="Aggregates.Header.Name" id="0U701">Nom</data>
  <data name="Aggregates.Header.Sample" id="0V701">Exemple</data>
  <data name="Aggregates.NoneLine" id="00801">&lt;i&gt;Aucun&lt;/i&gt;</data>
  <data name="Style.Aggregate.Name" id="01801">Style graphique {0}</data>
  <data name="Style.Paragraph.Name" id="02801">P.Style {0}</data>
  <data name="Style.Character.Name" id="03801">C.Style {0}</data>
  <data name="Style.Paragraph.Base" id="04801">P.Normal</data>
  <data name="Style.Character.Base" id="05801">C.Normal</data>
  <data name="Color.Rgb" id="06801">RVB</data>
  <data name="Color.Cmyk" id="07801">CMJN</data>
  <data name="Color.Gray" id="08801">Gris</data>
  <data name="Color.Alpha" id="09801">a</data>
  <data name="Color.RegistrationBlack" id="0A801">Noir repérage</data>
  <data name="Color.Black" id="0B801">Noir</data>
  <data name="Color.White" id="0C801">Blanc</data>
  <data name="Color.LightGray" id="0D801">Gris clair</data>
  <data name="Color.DarkGray" id="0E801">Gris foncé</data>
  <data name="Color.Red" id="0F801">Rouge</data>
  <data name="Color.Yellow" id="0G801">Jaune</data>
  <data name="Color.Green" id="0H801">Vert</data>
  <data name="Color.Cyan" id="0I801">Cyan</data>
  <data name="Color.Blue" id="0J801">Bleu</data>
  <data name="Color.Magenta" id="0K801">Magenta</data>
  <data name="File.Model.Empty" id="00A01" mod="1">Document vide</data>
  <data name="Question.ManyObjects" id="0L801">Voulez-vous vraiment transformer {0} objets ?</data>
  <data name="Error.BadFile" id="0M801">Type de fichier incorrect.</data>
  <data name="Error.BadImage" id="0N801">Format d&amp;apos;image inconnu.</data>
  <data name="Error.NoBitmap" id="0O801">Aucune image à exporter.</data>
  <data name="Error.Share" id="0P801">Impossible de distribuer les objets,&lt;br/&gt;car ils sont trop serrés.</data>
  <data name="Error.Combine" id="0Q801">Un ou plusieurs objets n&amp;apos;ont pas pu être combinés.</data>
  <data name="Error.Uncombine" id="0R801">Un ou plusieurs objets n&amp;apos;ont pas pu être scindés.</data>
  <data name="Error.ExistingText" id="0OB01">La présence de textes empêche l&amp;apos;enregistrement de l&amp;apos;icône.&lt;br/&gt;Il faut convertir ces objets en courbes avant l&amp;apos;enregistrement.</data>
  <data name="Error.ToBezier" id="0S801">Un ou plusieurs objets n&amp;apos;ont pas pu être convertis en courbes.</data>
  <data name="Error.ToPoly" id="0T801">Un ou plusieurs objets n&amp;apos;ont pas pu être convertis en droites.</data>
  <data name="Error.Fragment" id="0U801">Un ou plusieurs objets n&amp;apos;ont pas pu être fragmentés.</data>
  <data name="Error.Boolean" id="0V801">Opération impossible.</data>
  <data name="Error.NoText" id="00901">Le document ne contient aucun texte.</data>
  <data name="Error.NotFound" id="01901">Le texte recherché n&amp;apos;existe pas dans ce document.</data>
  <data name="Error.FileDoesNoetExist" id="03901" mod="1">Le fichier n&amp;apos;existe pas.</data>
</bundle>