<?xml version="1.0" encoding="utf-8"?>
<bundle name="Strings" type="String" culture="fr">
  <data name="Image.Description" id="0">Taille: {0} × {1}&lt;br/&gt;Format: {2}</data>
  <data name="Author" id="01" about="Cf. Common.Support.Tests">Pierre Arnaud</data>
  <data name="Null" id="02" about="Always NULL string">&lt;null/&gt;</data>
  <data name="CopyrightHolder" id="03">Pierre Arnaud &amp;amp; EPSITEC SA</data>
  <data name="CodeGenerator.SourceFileHeader" id="1">//  --------------------------------------------------------------------------- &lt;br/&gt;//  ATTENTION !&lt;br/&gt;//  Ce fichier a été généré automatiquement. Ne pas l&amp;apos;éditer manuellement, car &lt;br/&gt;//  toute modification sera perdue. &lt;br/&gt;//  --------------------------------------------------------------------------- &lt;br/&gt;</data>
</bundle>